postgresql/vmaas_db_schema.sql
Fixing ERROR:  schema "rpm" does not exist.
=> these functions are defined in current schema, not in rpm schema

database/vmaas_db_postgresql.sql
Few one-line patches for schema, resizing 2 text columns and adding various unique constrains.
=> Adjust column size and uniqueness

reposcan/dummy_crawler.sh
The real crawler will crawl via Red Hat CDN, download and parse repodata.
For now, I just add a predefined list of repositories.
=> add dummy crawler.

reposcan/database/package_store.py
=> unify sha and sha1 types

reposcan/repodata/repository_controller.py
=> check if repository is already synced

webapp/errata.py
=> fix duplicate results caused by joined CVE table

webapp/app.py
=> api: fix way of passing input data in POST request

reposcan/dummy_crawler.sh, reposcan/dummy_repolist.txt
Small fix, run command once instead of 16 times.
=> sync repositories at once

reposcan/wait-for-postgres.sh, webapp/wait-for-postgres.sh
fixing
vmaas_reposcan | psql: could not connect to server: Connection refused
vmaas_webapp | psql: could not connect to server: Connection refused
=> silence psql retries

database/vmaas_db_postgresql.sql, reposcan/database/update_store.py
Added columns to 'errata' to hold more errata-metadata, and taught erposcan to fill them in (it already knew about their existence, just had nowhere to store)
=> Fill in more errata metadata

webapp/Dockerfile, webapp/app.py
=> remove unused python2-falcon dependency

webapp/updates.py
Errata can be associated with several repos, so now we are checking package repo IDs matching to some errata repo IDs.
=> api: updates: fix for the issue #70

webapp/updates.py
Use exact matching for architectures.
=> api: updates: take architecture into account

README.md, docker-compose.devel.yml, docker-compose.yml, reposcan/Dockerfile, reposcan/entrypoint.sh, scripts/devel-compose, webapp/Dockerfile, webapp/entrypoint.sh
Slightly modified compose to make development easier.
How to instructions added to the end of README.
=> Developer setup

database/vmaas_db_postgresql.sql, reposcan/database/cve_store.py
According to API requirements, I'm adding support for parsing additional CVE data.
=> Add support for parsing CVE links and CWEs

webapp/updates.py
NEVRA kernel-2.6.32-131.0.15.el6.x86_64 is an "at first release" NEVRA. Handing it to updates generates
vmaas-webapp | HTTPServerRequest(protocol='http', host='localhost:8080', method='POST', uri='/api/v1/updates', version='HTTP/1.1', remote_ip='172.18.0.1', headers={'Content-Length': '21196', 'Expect': '100-continue', 'Content-Type': 'application/json', 'Host': 'localhost:8080', 'Accept': '*/*', 'User-Agent': 'curl/7.55.1'})
vmaas-webapp | Traceback (most recent call last):
vmaas-webapp |   File "/usr/lib64/python2.7/site-packages/tornado/web.py", line 1412, in _execute
vmaas-webapp |     result = method(*self.path_args, **self.path_kwargs)
vmaas-webapp |   File "/app/app.py", line 48, in post
vmaas-webapp |     response['update_list'] = updates.process_list(cursor, packages_to_process) …
=> Fix fatal KeyError when NEVRA not associated with an erratum

docker-compose.yml, openshift-deployment.yml, scripts/docker-push.sh, scripts/new-release.sh
With these changes it should be possible to create releases according to instructions on https://github.com/RedHatInsights/vmaas/wiki/ReleaseProcess.
Note: merge after #84 which renames `docker-compose.yaml` to `docker-compose.yml`
=> Add support for release branching and deployment

scripts/docker-push.sh
fixing "fatal: ambiguous argument 'HEAD..master': unknown revision or path not in the working tree."
=> compare last commit only

scripts/github-fetch-pullrequest
simplifies testing of pull requests
copy from https://github.com/spacewalkproject/spacewalk/blob/master/scripts/github-fetch-pullrequest
=> add script for simple fetching and rebasing pull request

webapp/Dockerfile
webapp is currently broken:
```
PostgreSQL is up - executing command
Traceback (most recent call last):
File "/app/app.py", line 8, in <module>
from database import Database
ImportError: No module named database
```
bug from #94
=> database.py is missing in image

database/vmaas_db_postgresql.sql, reposcan/database/product_store.py, reposcan/database/repository_store.py, reposcan/repodata/repository.py, reposcan/repodata/repository_controller.py, reposcan/reposcan.py
Product and content set data come from input JSON as described in last example [here](https://github.com/RedHatInsights/vmaas/wiki/ReposcanApi).
=> Import product and content set info

webapp/vmaas
fixes changes in dc49277f8d64ba531256495dc24f3acab646fb65
=> fixed cli according to "reusable API changes"

webapp/app.py
additional changes for the commit 3eb717cc1b7cc3c01c8af58a86d5e6b93d4cfea7
=> api: updates: for GET request handling we need to match packages name.

webapp/app.py, webapp/cve.py, webapp/updates.py
=> encapsulate api methods into classes

webapp/app.py, webapp/errata.py
new errata api.
fields requiring data:
- type
- summary
- bugzilla list
- reference list
=> Add errata api implementation

webapp/app.py
It also sets Content-Type: application/json; charset=UTF-8
=> api: use JSON auto-formating by Tornado.

webapp/app.py
http://www.tornadoweb.org/en/stable/web.html#tornado.web.RequestHandler.write
=> api: according to the official documentation to write the output to the network we need to use the flush() method.

webapp/vmaas
all API methods are implementeed as classes, so we need to instantiate them and use their methods.
=> api: cli: additional fixes for 06d1ffad577535dbb0c432ccb13bee8259077696.

reposcan/nistcve/cve_controller.py
This requires #133 to be merged first because import is now failing.
=> sync even older CVEs

webapp/updates.py
This is a fix for Issue #115. I added filtering for erratum, and include it only in case it has any CVE associated.
=> api: updates: fix issue #115. API method updates should return security-related erratum by default.

database/vmaas_db_postgresql.sql, reposcan/database/update_store.py, webapp/errata.py
This PR partially addresses Issue #119.
=> add missing type and summary fields to errata

reposcan/database/cve_store.py
=> 140 - hint PostgreSQL to cast NULL values properly

reposcan/database/database_handler.py, reposcan/reposcan.py
=> 132 - rollback any pending transaction when error occurs in repo or cve scan

webapp/cve.py
=> 160 - Update cve api with cvss3_score

webapp/updates.py
Partly fixes issue #120:
too-many-nested-blocks
invalid-name
=> api: updates: fix pylint updates

webapp/updates.py
=> fixing merge of PR#158

webapp/repos.py, webapp/updates.py
before:
- only updates from same repository are found
after:
- updates from repositories provided by same product are found (allows e.g. find update for pkg from optional in base repo and vice versa)
- releasever of original repo and update repo have to be same (prevents e.g. to update el6 package to el7 package because el6 and el7 are same product), it's possible to enhance it in future - specify allowed releasevers in request similarly as we specify repo labels
=> find updates in repositories of same product

webapp/updates.py
=> return also security updates without associated CVEs

webapp/vmaas
This fixes TypeError: __init__() takes exactly 3 arguments (2 given)
=> cli: additional fix for the commit 749b1e5b.

.travis.yml, reposcan/Dockerfile, reposcan/database/cve_store.py, reposcan/nistcve/cve_controller.py, webapp/Dockerfile, webapp/app.py, webapp/cve.py, webapp/errata.py, webapp/utils.py
Also unified timestamp parsing across the apllication.
=> Added modified_since filter to /cves and /errata

reposcan/nistcve/cve_controller.py
=> fix TypeError: Parser must be a string or character stream, not NoneType

webapp/updates.py
=> fix #208 - use description and summary from correct nevra

webapp/vmaas
This PR contains two fixes:
1) Improved error handling
2) CveAPI doesn't require repocache
=> fix vmaas cli tool

reposcan/nistcve/cverepo.py, reposcan/reposcan.py
* reused class attributes instead of function parameters
* moved static functions into classes where they logically belongs
* enabled NIST data url override (for testing)
=> reposync code improvements

docker-compose.yml
increase disk size requirements for reposync tmp cache and persistent database
=> increase disk requirements for Openshift deployment

database/vmaas_db_postgresql.sql, reposcan/common/dateutil.py, reposcan/common/string.py, reposcan/database/cve_common.py, reposcan/database/cve_store.py, reposcan/database/cvemap_store.py, reposcan/download/downloader.py, reposcan/redhatcve/cvemap.py, reposcan/redhatcve/cvemap_controller.py, reposcan/repodata/primary.py, reposcan/repodata/repomd.py, reposcan/repodata/updateinfo.py, reposcan/reposcan.py
=> Sync CVEs from redhat cvemap.xml 

webapp/Dockerfile, webapp/app.py, webapp/gen.py
This add thread pool for the blocking code. Then process result in async way. When a response is ready the main IOLoop thread sends data back to the client.
=> api: webapp: add an ability to process requests in parallel.

openshift-deployment.yml
small fix to prevent error in output
=> cancel any already running rollout before triggering new one

.travis.yml, webapp/Dockerfile, webapp/app.py, webapp/updates.py
Also adjust existing ValueError to return more useful error-info
=> Fix #252 - validate incoming /updates json, using jsonschema

webapp/updates.py
This changes the updates api to do a single db query where it used to do one db query per package specified in the request.  This implementation does the evr comparison in the python/webapp code.  The rpmver_array() and other evr related functions and types are no longer required in the database.
In my tests, what used to take 22 seconds now takes 15 with this change.
=> Make updates api db query more efficient

docker-compose.yml, reposcan/Dockerfile, reposcan/entrypoint.sh, reposcan/rsyncd.conf, webapp/Dockerfile, webapp/cache.py
Openshift can't be configured to use shared storage among containers. So we have to copy data over.
=> Copy disk dump via rsync

reposcan/Dockerfile, webapp/Dockerfile
openshift runs containers as non-root let's do the same in docker
to catch issues during development not deployment ;)
=> run as non-root user even in docker

reposcan/exporter.py, reposcan/reposcan.py
currenly runs only after AllSyncHandler request
=> run exporter after each sync task automatically

conf/webapp.env, webapp/Dockerfile, webapp/app.py
This give us some performance boost.
=> webapp: run several tornado.httpserver.HTTPServer instances.

webapp/app.py, webapp/updates.py
Multi-level cache for the `webapp` container. It also contains Garbage Collector.
=> api: updates: add multilevel cache based on SplayTree.

webapp/updates.py, webapp/utils.py
=> Fixing ISEs for wrong repo and bad date spec

webapp/repos.py
=> fix #316 - skip non-existent repository

reposcan/entrypoint.sh, reposcan/exporter.py, webapp/entrypoint.sh
=> don't export non-security errata details

webapp/app.py
Removing duplicated code from 4 places and putting it into one place.
=> extract duplicated code into super class

reposcan/Dockerfile, reposcan/reposcan.py, scripts/new-release.sh, webapp/Dockerfile, webapp/app.py
1. In apidoc Swagger UI
2. Using GET request on /api/v1/version/
=> display currently running vmaas version

webapp/app.py
Fixing an issue where incorrectly formed regular expression ended up with ISE 500.
=> fix #343 - add handling of malformed regular expressions

reposcan/reposcan.py
https://docs.python.org/3/library/multiprocessing.html
"Callbacks should complete immediately since otherwise the thread which handles the results will get blocked."
=> fix #345 - do not run export in callback, it's a blocking operation

reposcan/common/logging.py, reposcan/reposcan.py, webapp/app.py, webapp/utils.py
Fixes #334 
* uses logging module in both reposcan and webapp,
* logs container id,
* logs app version,
* in case of IS logs whole traceback.
=> Logging improvements

webapp/app.py, webapp/cve.py, webapp/errata.py, webapp/packages.py, webapp/repos.py, webapp/updates.py, webapp/vmaas
This adds a v2 updates api, which no longer returns package summary and description.
=> Add v2 updates api

openshift-deployment.yml
using like:
$ ansible-playbook openshift-deployment.yml --tags up -e "app_id=1"
that will create openshift components with id "1" instead of last commit id
=> support specifying custom app_id

conf/database-connection-admin.env
Environment variables with username and password are used to create a new account in the DB.
=> add comments on environment variable for the database container.

database/vmaas_db_postgresql.sql, reposcan/database/modules_store.py, reposcan/database/object_store.py, reposcan/database/package_store.py, reposcan/database/repository_store.py, reposcan/database/update_store.py, reposcan/repodata/modules.py, reposcan/repodata/repository.py, reposcan/repodata/repository_controller.py
Downloads, parses and stores all relevant info regarding modules into the VMaaS database.
=> Store module metadata in the VMaaS DB

.env, .gitignore, reposcan/reposcan.py, webapp/app.py
- run vmaas and vuln-engine on same docker network
- identify webapp and listener connections and send confirmation to listener once all webapps are refreshed
see also https://github.com/RedHatInsights/vulnerability-engine/pull/23
=> notify listener when all webapps are refreshed

.travis.yml, webapp/app.py, webapp/test/test_cve.py, webapp/test/test_errata.py, webapp/test/test_repos.py, webapp/test/test_utils.py
- fix memory leaks in coroutines
- fix bunch of testing issues
- disable tests on Python 2.7 and 3.5
=> fix memory leaks in coroutines

webapp/app.py
- Added probe to v2/updates (oops)
- Added Histogram to cve/errata/repos (in addition to /updates)
- Renamed invocations-counter to make it more clear when collected by the prom-server
=> prometheus probe tweaks

database/vmaas_db_postgresql.sql, reposcan/database/modules_store.py, reposcan/repodata/modules.py
modules come with version, store it into database as well
so we can track differences between their versions
=> store module version information

reposcan/reposcan.py
if webscoket wasn't available at the time sync task finished the application
raised a traceback and stopped responding to all other sync requests returning
HTTP 429 to all requests until that sync task was manually cancelled
this commit adds storing message into a queue in case ws is not available
and automatic sending of all messages which should have been
sent in the meantime
=> store messages if ws is not available and send them once it's up

webapp/app.py
same thing as in reposcan, eventual disconnects from webscoket
when we're about to write in it are not handled well
=> store messages and send them later in case of websocket outage

reposcan/repodata/modules.py
fixes cases when modulemd-defaults were referecing not exisitng
streams/profiles
=> fix non-consistent modulemd and modulemd-defaults

database/vmaas_db_postgresql.sql, reposcan/database/modules_store.py, reposcan/repodata/modules.py
modules are distinguished by N:S:V:C
=> store module context

reposcan/database/update_store.py
Unfortunately I was not able to reproduce the issue, but according to error message and code, this should fix the issue.
=> fix sync failures during package,errata,module disassociation

reposcan/nistcve/cvejson.py
=> #456 - recognize that NIST-json can be utf-8

reposcan/test/conftest.py, reposcan/test/test_exporter.py, reposcan/test_data/exporter/exporter_test_data.sql
Add tests for exporter.py.
I noticed a likely issue in exporter exporting modules data.  I'll open an issue for that.
=> add reposcan exporter unit tests

Dockerfile-webapp-qe, webapp/requirements_qe.txt
Needed in jenkins
pinned to `coverage==4.5.3`
=> Coverage is needed in webapp-qe dockerfile

reposcan/common/batch_list.py, reposcan/common/logging.py, reposcan/database/cve_store.py, reposcan/database/cvemap_store.py, reposcan/database/cverepo_store.py, reposcan/database/package_store.py, reposcan/database/repository_store.py, reposcan/database/update_store.py, reposcan/download/downloader.py, reposcan/download/unpacker.py, reposcan/repodata/repository_controller.py
- reduce number of INFO messages (available as debug now) - it's easier to find errors in log now
- add progress info (logged every 60s by default) to easily find out progress of sync task
=> add better progress logging

webapp/app.py
=> fixed webapp /repo API endpoint example

database/vmaas_db_postgresql.sql, reposcan/common/rpm.py, reposcan/common/test/test_rpm.py, reposcan/database/package_store.py, reposcan/database/test/test_package_sort.py, reposcan/database/test/test_repository_store.py, reposcan/test_data/exporter/exporter_test_data.sql
added support for ~ and ^ notation (sorting)
- sql function rpmver_array replaced with python one
- added several tests for related functions
=> packages sorting with ~ and ^ notation

README.md
- joined multiple following commands using `~~~bash`
notation
- improved some formating
=> simplified README.md

reposcan/common/rpm.py, reposcan/common/test/test_rpm.py, reposcan/database/package_store.py
get source rpm epoch from binary rpm if
no source rpm epoch provided in primary repo data
=> fix source rpm epoch

reposcan/common/rpm.py, reposcan/exporter.py, reposcan/test/test_exporter.py, reposcan/test_data/exporter/exporter_test_data.sql, webapp/app.py, webapp/cache.py, webapp/packages.py, webapp/test/data/cache.yml, webapp/test/schemas.py, webapp/test/test_packages.py
Add binary packages list to response of `/api/v1/packages` endpoint.
=> Add binary packages list to source package info

webapp/cve.py, webapp/errata.py, webapp/repos.py, webapp/test/test_utils.py, webapp/utils.py
Add filter to check existance in cves, repos and errata API
During solving this issue I found that cves and errata API has the same problem
=> Inconsistencies in vmaas /api/v1/repos/ response

reposcan/database/modules_store.py, reposcan/database/repository_store.py, reposcan/database/update_store.py, reposcan/pkgtree.py, reposcan/repodata/modules.py, reposcan/repodata/repository.py, reposcan/repodata/test/test_modules.py, reposcan/test_data/repodata/modules.yaml
This is to address Issue # 506 which requested that module information be added to pkgtree output.
=> Add modules to pkgtree output

reposcan/common/rpm.py, reposcan/common/test/test_rpm.py, reposcan/database/modules_store.py, reposcan/database/package_store.py
This for VMAAS-606 sprint task.
=> fix and reuse common rpm.parse_rpm_name() method

scripts/generate_manifest.sh
~~~bash
./scripts/generate_manifest.sh webapp/Dockerfile manifest_web_app.txt
cat manifest_web_app.txt
~~~
=> added manifest generator script

reposcan/pkgtree.py, reposcan/repodata/modules.py, reposcan/test_data/repodata/modules.yaml
=> fix module parsing

reposcan/common/fileutil.py, reposcan/database/database_handler.py, reposcan/download/unpacker.py, reposcan/exporter.py, reposcan/pkgtree.py
This updates error handling in code that uses NamedCursor, which is exporter.py and pkgtree.py.
=> better NamedCursor error handling

database/Dockerfile, database/Dockerfile.rhel7, reposcan/Dockerfile, reposcan/Dockerfile.rhel7, scripts/generate_manifest.sh, webapp/Dockerfile, webapp/Dockerfile.rhel7, websocket/Dockerfile, websocket/Dockerfile.rhel7
- Store `manifest.txt` to component images.
- Print manifest component in build stage.
=> Added manifest to the component images

docker-compose.test.yml, reposcan/requirements.txt, requirements_tests.txt, run_tests.sh, scripts/check_deps_versions.sh, webapp/requirements.txt, webapp/requirements_qe.txt, websocket/requirements.txt
=> Added deps versions checker

reposcan/test/test_batchlist.py, webapp/test/test_updates.py
I added few tests for the vmaas. exactly:
- tests for the batchlist data structure
- tests for splay tree implementation used in webapp (updates.py)
- tests for rpm parsing in reposcan
=> Add few reposcan and webapp unit-tests.

webapp/app.py, webapp/probes.py
- added generic logging request info
- added generic metrics for request exposing
=> Generic metrics

webapp/repos.py
=> fix duplicated results

reposcan/Dockerfile, reposcan/Dockerfile.rhel7, webapp/Dockerfile, webapp/Dockerfile.rhel7, webapp_utils/Dockerfile, webapp_utils/Dockerfile.rhel7, websocket/Dockerfile, websocket/Dockerfile.rhel7
This pull request fixes for me the issue 
```
pip install --upgrade pip pipenv
OSError: [Errno 18] Invalid cross-device link:
```
when trying to use `podman-compose`: https://github.com/containers/podman-compose
=> fix Docker files for podman-compose

Jenkinsfile, Pipfile, Pipfile.lock, webapp/Dockerfile, webapp/Dockerfile-qe, webapp/Dockerfile.rhel7, webapp/Pipfile, webapp/app.py, webapp/entrypoint.sh, webapp/main.py, webapp/test/conftest.py, webapp/test/test_app.py, webapp/webapp.spec.yaml
This PR migrates webapp from Tornado to Connexion and aiohttp.
These changes incur some performance penalties in the worst case, since current implementation is 
performing further input validation, even after connexion validated input body.
Some quick testing showed that latencies under load have worsened, but # Req/s remains roughly the same, and latency under normal conditions is unaffected. [Results](https://drive.google.com/open?id=1ewR-4tpAoCqp7ROyTLyjFmp33-6oh6MOgaCPVvfP9Y0) ( Results from this commit are in the aiohttp columns)
=> Migrate webapp to connexion

webapp/app.py
This adds Code for handling HttpError inside handle_request call. Previously, this error was caught by the general Exception case, and turned into an 500 response.
=> Handle HttpError in handle_request

Jenkinsfile
PR with updated pins to iqe-tests is submitted but it is not merged yet
=> workaround for old pinned version

common/webapp_utils.py, webapp_utils/errata.py, webapp_utils/package_repositories.py, webapp_utils/packages.py, webapp_utils/webapp-utils.yml
- New GET method on packages/repositories to get repositories list on single package
- Refactorization to remove redundant code
- Bugfix of ISE on /package
=> Utils packages api bugfix and new get method

reposcan/reposcan.py
Disables the signal handlers when creating new multiprocessing pools, so that they don't inherit custom handlers. This used to kill application when receiving sucessive /api/v1/task/cancel calls.
Also kill multiprocessing pool on receiving killing signal, In order to correctly shut down the application.
=> Fix signal handlers killing application in combination with multiprocessing

docker-compose.devel.yml
=> Fix module common not found error in devel-compose

scripts/list_rhsm_repos.py
- rhsm cert should be optional due to feature in reposcan to read it from env
- pretty print the output
=> fix repolist generation script

Pipfile, Pipfile.lock, README.md, doc/developer_mode.md, scripts/devel-compose
Fix for starting app in developer mode with podman. More Info in Readme.md.
Example:
```
sudo ./scripts/devel-compose up --build
```
```
sudo podman exec -it vmaas-webapp bash
```
=> Podman developer mode

reposcan/exporter.py, reposcan/test/test_exporter.py, webapp/app.py, webapp/updates.py, webapp/webapp.spec.yaml
- export all errata to dump
- add new /v3/updates API to return all updates/security only if `security_only` parameter is set
=> support to return all updates

Jenkinsfile
due to refactoring in tests repo
=> chore: update vmaas tests path

docker-compose.devel-podman.yml, websocket/Dockerfile, websocket/Dockerfile.rhel7, websocket/entrypoint.sh
Fixes wrong ownership of /data in podman and unifies websocket entrypoint.
=> Podman setup fixes

reposcan/database/repository_store.py
this is a hotfix to this #640 PR
=> deleting vmaas repos fails due to module foreign key references

reposcan/database/cvemap_store.py, reposcan/mnm.py, reposcan/redhatcve/cvemap_controller.py, reposcan/repodata/repository_controller.py, reposcan/reposcan.py
add metrics to count failed imports of cves and repos
=> alert when repo/CVE import in reposcan fails

database/vmaas_db_postgresql.sql, reposcan/database/update_store.py, webapp/errata.py, webapp/webapp.spec.yaml
fix(database): store null severity in errata table
fix(reposcan): import null severity to db
fix(webapp): return null instead of empty string
should I create 3 different commits or 1 will be ok?
=> return null errata severity instead of string "None"

Jenkinsfile
https://github.com/bsquizz/ocdeployer/issues/37
=> chore: workaround ocdeployer bug

.github/workflows/main.yml, Jenkinsfile
Jenkins will work after merge of https://github.com/RedHatInsights/e2e-deploy/pull/1106
=> chore: run Actions on PR to master/stable, Jenkins against master/stable

Pipfile, Pipfile.lock, reposcan/Pipfile, reposcan/Pipfile.lock, reposcan/mnm.py, reposcan/repodata/repository_controller.py
check if the expiration date of the certificate and set status in Prometheus that certificate is valid, expire soon or expired.
=> prevent unnoticed vmaas CDN cert expiration

Dockerfile.test, reposcan/Dockerfile, webapp/Dockerfile, webapp/Dockerfile-qe, webapp_utils/Dockerfile, websocket/Dockerfile
This reverts commit ec23cb5226ded5d245c3bfce244f190481ad676c.
=> re enable pipenv check

reposcan/database/cvemap_store.py
This bug fix related to task with this PR RedHatInsights/vulnerability-engine#427
Add deleting CVEs from DB if CVE was removed from cvemap.xml
also, it replaces this https://github.com/RedHatInsights/vmaas/pull/598 PR
=> NIST CVEs in vulnerability engine bug fix in vmaas

Dockerfile.test, docker-compose.devel.yml, docker-compose.test.yml, reposcan/Dockerfile, scripts/devel-compose, webapp/Dockerfile, webapp/Dockerfile-qe, webapp_utils/Dockerfile, websocket/Dockerfile
this PR obsoletes #690 
curently pyup.io is down which break new image builds
=> make an easy way to disable pipenv check when necessary

webapp/app.py, webapp/patches.py, webapp/test/schemas.py, webapp/webapp.spec.yaml
new /patches API to show only simple errata list
=> feat(webapp): new API to list only applicable errata to a package list

README.md, docker-compose.yml, reposcan/Dockerfile, scripts/devel-compose, webapp/Dockerfile, webapp_utils/Dockerfile, websocket/Dockerfile
allows commands like:
$ PIPENV_CHECK=0 docker-compose up --build
=> chore: allow to get PIPENV_CHECK variable from host environment

reposcan/exporter.py, reposcan/reposcan.spec.yaml, webapp/app.py
fixing bug when first dump is not loaded
=> fix: there may not be any dump loaded

reposcan/exporter.py, webapp/app.py, webapp/cache.py, webapp/rpm_pkg_names.py, webapp/srpm_pkg_names.py, webapp/test/data/cache.yml, webapp/test/schemas.py, webapp/test/test_cache.py, webapp/test/test_rpm_pkg_names.py, webapp/test/test_srpm_pkg_names.py, webapp/webapp.spec.yaml
/rpms api endpoint for webapp, it allows to get rpm names by srpm_name_list and filter it by content_set_list, also it allows querying content_set by rpm_name_list
=> Product Security would like to query for binary RPM names for an SRPM name

.github/workflows/main.yml
new needed secrets
`OPENSHIFT_SERVER_URL`
`OPENSHIFT_TOKEN` - svc account with edit rights to vmaas-qe project
`OPENSHIFT_WEBAPP_URL`
`OPENSHIFT_REPOSCAN_URL`
`VMAAS_BOT` - github token of vmaas bot
=> chore: deploy to openshift

webapp/updates.py
including updates from different repos of the same product
confuses users because they see updates from repos which they do not
have enabled
=> fix(webapp): removed redundant product check

webapp/webapp.spec.yaml
=> refactor: tag experimental endpoints

database/upgrade_scripts/001-severity-to-null.sql, database/vmaas_db_postgresql.sql, reposcan/database/test/conftest.py, reposcan/database/test/test_upgrader.py, reposcan/database/test/test_upgrades.py, reposcan/database/upgrade.py
- The None severities are now changed to the SQL null
=> feat(webapp): unify errata severity none to null

reposcan/exporter.py, webapp/cache.py, webapp/srpm_pkg_names.py, webapp/test/test_cache.py
opencv RPMs for rhel-8-for-*-rpms not returned
=> package_names/(s)rpms: No hits for libbluray and other packages

reposcan/reposcan.spec.yaml, webapp/webapp.spec.yaml
Finished VMAAS-1247, added enums and date-time format.
=> Docs: specify possible values in schema

docker-compose.yml
we have only one Dockerfile so let's build it only once
=> fix: build app image only once

docker-compose.devel-podman.yml, docker-compose.devel.yml, entrypoint.sh
=> fix: update developer mode to new single container

Pipfile, Pipfile.lock, common/logging_utils.py, docker-compose.yml, reposcan/reposcan.py, run_tests.sh, webapp/app.py, websocket/test/test_run_websocket.py, websocket/test/test_websocket.py, websocket/test/test_websocket_mocked.py, websocket/websocket.py
- Add readiness check to webapp
- Update websocket to take webapp state into account
- When refreshing, attempt to keep one webapp in running state
=> [WIP] Progressive refreshing of webapps

Dockerfile, Dockerfile.test, common/rpm.py, common/webapp_utils.py, docker-compose.devel-podman.yml, reposcan/database/modules_store.py, reposcan/database/package_store.py, reposcan/pkgtree.py, reposcan/test/test_rpm.py, webapp/packages.py, webapp/pkgtree.py, webapp/test/test_utils.py, webapp/updates.py, webapp/webapp.spec.yaml, webapp_utils/errata.py, webapp_utils/package_repositories.py, webapp_utils/packages.py
Fixing bz1875706
Adds new "latest_only" option to input json.
=> add option to return updates for latest packages only

webapp/app.py
fix(webapp): check if websocket is open before message is sent and ensure concurrency
VMAAS-1315
asyncio: [ERROR] Task exception was never retrievedfuture: <Task finished coro=<Websocket._refresh_cache() done, defined at /vmaas/webapp/app.py:422> exception=AttributeError("'NoneType' object has no attribute 'send_str'",)>'Traceback (most recent call last):\n  File "/vmaas/webapp/app.py", line 428, in _refresh_cache\n    await self.report_version()\n  File "/vmaas/webapp/app.py", line 476, in report_version\n    await self.websocket.send_str(f"version {BaseHandler.db_cache.dbchange.get(\'exported\')}")\nAttributeError: \'NoneType\' object has no attribute \'send_str\''|
=> VMAAS-1315: fix(webapp): check if websocket is open before message is sent and ensure concurrency

reposcan/mnm.py, reposcan/reposcan.py, reposcan/reposcan.spec.yaml, reposcan/test/test_case.py, scripts/turnpike-mock
no complete authentication/authorization done here, we just parse&log header from turnpike
=> VULN-1421 - fix(reposcan): replace github auth with turnpike

webapp/test/schemas.py, webapp/test/test_app.py, webapp/test/test_vulnerabilities.py, webapp/vulnerabilities.py, webapp/webapp.v3.spec.yaml
by default evaluate based on repodata + OVAL
allow to evaluate using exclusively repodata or OVAL by parameters
=> feat(webapp): define interface for patched/unpatched CVEs and OVAL evaluation toggles

webapp/test/schemas.py, webapp/test/test_updates.py, webapp/updates.py
Refactored webapp/updates.py to be easier to read.
=> updates.py refactor

database/upgrade_scripts/003-add-third-party.sql, database/vmaas_db_postgresql.sql, reposcan/database/product_store.py, reposcan/database/repository_store.py, reposcan/database/test/test_repository_store.py, reposcan/exporter.py, reposcan/reposcan.py, reposcan/reposcan.spec.yaml, reposcan/test_integration/test_integration.py
Implement reposcan changes to include third party content.
=> Third-party content support - Reposcan

pr_check.sh
Signed-off-by: bennyturns <bturner@redhat.com>
=> Updated pr check to use absolute paths

webapp/pkgtree.py, webapp/test/test_pkgtree.py, webapp/webapp.v3.spec.yaml
- return_{errata, repositories, summary, description}
=> feat(webapp): add new /pkgtree endpoint options

vmaas/webapp/pkgtree.py, vmaas/webapp/test/test_pkgtree.py, vmaas/webapp/webapp.v3.spec.yaml
- to be consistent with /cves /errata endpoints
=> fix(webapp) - add "modified_since" to /v3/pkgtree response

vmaas/webapp/cve.py, vmaas/webapp/errata.py, vmaas/webapp/packages.py, vmaas/webapp/patches.py, vmaas/webapp/repos.py, vmaas/webapp/test/schemas.py, vmaas/webapp/test/test_app.py, vmaas/webapp/test/test_cve.py, vmaas/webapp/test/test_errata.py, vmaas/webapp/test/test_repos.py, vmaas/webapp/test/test_updates.py, vmaas/webapp/test/test_vulnerabilities.py, vmaas/webapp/updates.py, vmaas/webapp/vulnerabilities.py, vmaas/webapp/webapp.v3.spec.yaml
- Removed returning of some filters: `modified_since`, `published_since`
- Added `last_change` in all endpoints
=> VULN-1347 refactor(webapp): make responses more consistent

vmaas/webapp/pkgtree.py, vmaas/webapp/test/test_pkgtree.py, vmaas/webapp/webapp.v3.spec.yaml
This reverts commit aee93a6a20d1bee6a9f4af45d07e1ae6d399c79a.
=> fix(webapp): revert: add "modified_since" to /v3/pkgtree response"

Pipfile, Pipfile.lock, vmaas/common/config.py
fixes connection to DB in ephemeral env
=> fix: default ssl mode can't be empty string

conf/reposcan.env, vmaas/reposcan/redhatoval/oval_controller.py
=> VMAAS-1369 - feat(reposcan): support filtering OVAL files

deploy/clowdapp.yaml, pr_check.sh
=> chore: run smoke tests using cji

Dockerfile, build_deploy.sh, pr_check.sh
=> chore: improve image build

vmaas/reposcan/database/oval_store.py
=> feat(reposcan): auto delete old oval items

vmaas/webapp/test/test_updates.py, vmaas/webapp/updates.py
=> fix(webapp): fix /updates test for arch "(none)"

conf/reposcan.env, vmaas/reposcan/exporter.py, vmaas/reposcan/reposcan.py, vmaas/webapp/cache.py, vmaas/webapp/errata.py, vmaas/webapp/test/data/cache.yml, vmaas/webapp/test/schemas.py, vmaas/webapp/webapp.v3.spec.yaml
- to dump exporter
- to dump loading
- to webapp API
=> feat: added "requires-reboot" errata field

vmaas/reposcan/repodata/test/test_updateinfo.py, vmaas/reposcan/repodata/updateinfo.py, vmaas/reposcan/test_data/repodata/updateinfo.xml
=> fix(reposcan): fixed advisory "reboot_suggested" value parsing

Dockerfile
- pgdg aarch64 repo is having issues with repo_gpgcheck
- psycopg has to built and it needs gcc, python3-devel, and libpq-devel (for pg_config)
=> chore: allow build on aarch64

deploy/clowdapp.yaml, vmaas/common/config.py, wait_for_services.py
we cannot access websocket from init container in fedramp stage due to istio
=> chore: don't wait for websocket in init container

pr_check.sh
Opt out from building image, deploying to ephemeral, or running iqe tests in pr_check
In the future it will be possible to run tests based on the iqe requirement - running tests only for changed functionality/requirement of the app - https://github.com/RedHatInsights/bonfire/pull/120 (changes are needed in clowder as well)
=> chore: use labels in pr_check

vmaas/webapp/pkgtree.py, vmaas/webapp/test/data/cache.yml, vmaas/webapp/test/test_pkgtree.py, vmaas/webapp/test/test_utils.py
- Include third-party package repositories - not included before
- Exclude package with third-party repositories if needed
- VMAAS-1351
=> fix(webapp): Fix /pkgtree third-party repos info and third-party flag

vmaas/webapp/cache.py
=> fix(webapp): rebuild index array on cache reload

vmaas/webapp/packages.py, vmaas/webapp/test/test_app.py
=> chore: VMAAS-1353 modify /packages to retun package name always

vmaas/webapp/vulnerabilities.py
=> fix(webapp): use common function for parsing evr

pr_check.sh
depends on https://github.com/RedHatInsights/bonfire/pull/152
=> chore: keep pr_check namespace with label

Dockerfile, Dockerfile.test, scripts/pipenv-lock.sh, vmaas/reposcan/redhatcve/cvemap_controller.py
=> fix(reposcan): do not store 'None' string if last-modified header is not available

pr_check.sh
run only tests for requirements specified with labels
=> chore: more labels for pr check tests

vmaas/reposcan/database/oval_store.py, vmaas/reposcan/mnm.py, vmaas/reposcan/redhatoval/oval_controller.py, vmaas/reposcan/reposcan.py
=> chore(reposcan): add more counters in oval sync

vmaas/reposcan/database/upgrade.py
=> fix(reposcan): Fix vmaas_reader password setting

deploy/clowdapp.yaml
=> fix(webapp): Remove null probes in clowaddp.yaml

deploy/clowdapp.yaml
=> chore: remove legacy service objects

vmaas/webapp/cve.py
=> fix(webapp): in errata_associated CVE list include also CVEs found only in OVAL files (missing in repodata due to error)

vmaas/reposcan/database/cpe_store.py
=> fix(reposcan): EUS repos are mapped to CPEs of incorrect EUS version

deploy/clowdapp.yaml
=> VMAAS-1412: pass REPO_NAME_PREFIXES to webapp

conf/repolist.json
=> fix: rename epel repo to epel-8

vmaas/reposcan/exporter.py
=> chore: remove dump files in old format

vmaas-go/base/core/config.go, vmaas-go/go.mod, vmaas-go/go.sum, vmaas-go/webapp/controllers/updates.go, vmaas-go/webapp/controllers/utils.go, vmaas-go/webapp/controllers/vulnerabilities.go, vmaas-go/webapp/webapp.go
=> chore(vmaas-go): don't block on cache load

deploy/clowdapp.yaml
We need to use separate env vars for limits and requests, currently, vmaas fails in stage due to quota issue
=> fix: define cpu/memory limit/requests separately

vmaas-go/webapp/controllers/updates.go, vmaas-go/webapp/controllers/utils.go, vmaas-go/webapp/controllers/vulnerabilities.go
=> fix(vmaas-go): return 503 during cache reload

vmaas-go/webapp/controllers/utils.go, vmaas-go/webapp/webapp.go
=> fix(vmaas-go): don't proxy request when error is present

vmaas-go/go.mod, vmaas-go/go.sum
=> fix(vmaas-go): bump vmaas-lib version to fix arch compatibility

deploy/clowdapp.yaml, vmaas-go/base/core/config.go, vmaas-go/base/utils/config.go, vmaas-go/go.mod, vmaas-go/go.sum, vmaas-go/webapp/webapp.go
- close connection in vmaasProxy
- add option to run profiler
- fix missing env in clowdapp
- various optimizations from https://github.com/RedHatInsights/vmaas-lib/releases/tag/v0.2.3
=> fix(vmaas-go): optimizations

.github/workflows/db-docs.yml
=> chore: replace deprecated set-output command

vmaas/common/logging_utils.py
=> fix: watchtower params

pr_check.sh, vmaas-go/go.mod, vmaas-go/go.sum, vmaas-go/webapp/controllers/updates.go
lib changes
- https://github.com/RedHatInsights/vmaas-lib/commit/9549f8a5d1ef160e942d6557b79ede50ac6d4c95
- https://github.com/RedHatInsights/vmaas-lib/commit/c991822e1aba9a6be8a4f290e089b8d07fdd76ba
=> fix minor bugs in vmaas-go

Dockerfile, scripts/pipenv-lock.sh
=> chore: downgrade do ubi8 but with Python 3.9

Dockerfile, build_deploy.sh, deploy/clowdapp.yaml, vmaas/reposcan/reposcan.py
=> chore: build repolist to the image (FedRAMP)

Dockerfile, conf/cdappconfig.json, deploy/clowdapp.yaml, docker-compose.yml, entrypoint.sh, vmaas-go/base/core/config.go, vmaas-go/base/utils/config.go, vmaas/common/config.py, vmaas/reposcan/reposcan.py, vmaas/reposcan/reposcan.spec.yaml, vmaas/reposcan/rsyncd.conf, vmaas/webapp/app.py, vmaas/webapp/cache.py
=> chore: replace rsync with http

Dockerfile, conf/cdappconfig.json, deploy/clowdapp.yaml, docker-compose.yml, entrypoint.sh, vmaas-go/base/core/config.go, vmaas-go/base/utils/config.go, vmaas/common/config.py, vmaas/reposcan/nginx.conf.template, vmaas/reposcan/reposcan.py, vmaas/reposcan/reposcan.spec.yaml, vmaas/webapp/cache.py
reposcan webserver is single-threaded and serving large files is causing timeouts
=> chore: use nginx to serve dump files

docker-compose.yml, vmaas/common/slack_notifications.py
=> fix: handle exception when sending slack notification

vmaas-go/base/base.go, vmaas-go/base/core/config.go, vmaas-go/base/utils/awscloudwatch.go, vmaas-go/base/utils/config.go, vmaas-go/base/utils/core.go, vmaas-go/base/utils/gin.go, vmaas-go/base/utils/log.go, vmaas-go/go.mod, vmaas-go/go.sum, vmaas-go/webapp/middlewares/logger.go, vmaas-go/webapp/webapp.go
- randomize refresh period
- stream to file
=> chore: cache load improvements

vmaas-go/go.mod, vmaas-go/go.sum, vmaas/reposcan/exporter.py, vmaas/webapp/cache.py, vmaas/webapp/test/test_cache.py, vmaas/webapp/vulnerabilities.py
=> feat(webapp): return errata for manual remediations

deploy/clowdapp.yaml, vmaas/webapp/app.py
they are logged when app exits otherwise
=> fix SSL context usage in aiohttp

vmaas-go/go.mod, vmaas-go/go.sum, vmaas-go/webapp/controllers/utils.go
=> fix(vmaas-go): modules_list consistency with python

vmaas-go/go.mod, vmaas-go/go.sum
oval: Check module stream in evaluateModuleTest (20be8ac)
oval: Remove duplicates from UnpatchedCves list (9c48307)
modules: Find updates in modular errata for package from module when module is enabled (cd99eef)
=> fix(webapp-go): oval and modules fixes

vmaas-go/go.mod, vmaas-go/go.sum
=> feat(oval): unpatched cves take precedence

vmaas-go/go.mod, vmaas-go/go.sum
=> feat(oval): show package name, evra, cpe for unpatched cves

vmaas-go/go.mod, vmaas-go/go.sum
=> fix(modules): package from module with disabled repo

vmaas/webapp/updates.py, vmaas/webapp/vulnerabilities.py
=> fix: backport vmaas-go changes to py

vmaas-go/go.mod, vmaas-go/go.sum
return error if pkg epoch is required and any pkg in request is missing epoch
RHINENG-390
=> feat: add epoch_required request option

deploy/clowdapp.yaml
=> chore: change minReplicas -> replicas

vmaas-go/base/core/config.go, vmaas-go/base/utils/config.go, vmaas-go/go.mod, vmaas-go/go.sum
=> chore: improve vmaas-lib config

deploy/clowdapp.yaml
=> chore: add apiPath to bind APIs to correct paths

.github/workflows/lint.yml, vmaas-go/.golangci.yml, vmaas-go/base/core/config.go, vmaas-go/base/utils/config.go, vmaas-go/base/utils/gin.go, vmaas-go/go.mod, vmaas-go/go.sum, vmaas/webapp/webapp.v3.spec.yaml
=> feat: show package_name and evra in updates response

vmaas-go/go.mod, vmaas-go/go.sum
=> chore(vmaas-go): promote vmaas-lib

pr_check.sh
=> chore: re-enable disabled smoke tests

vmaas-go/go.mod, vmaas-go/go.sum, vmaas/reposcan/reposcan.py
=> RHINENG-1536: sorted availableUpdates

Dockerfile, vmaas-go/go.mod, vmaas-go/go.sum
=> fix: sort updates also by other fields

Pipfile.lock
- Updating packages in order to fix security vulnerabilities.
1. Pull branch and build docker image with new updated packages
2. Run the following to perform security scan: `docker run --rm --volume /var/run/docker.sock:/var/run/docker.sock --name Grype anchore/grype:latest "$(docker images --format '{{.Repository}}' |grep {insert image tag name})" --only-fixed`
3. The output should show no high or critical vulnerabilities.
=> Fix security vulnerabilities.

vmaas/webapp/cache.py, vmaas/webapp/repos.py, vmaas/webapp/test/data/cache-dump.sql, vmaas/webapp/test/data/cache.yml, vmaas/webapp/test/schemas.py, vmaas/webapp/test/test_repos.py
=> feat(webapp): return and display latest change of repo in vmaas

Dockerfile, vmaas/reposcan/redhatcpe/cpe_controller.py
=> fix: use new url for cpe dictionary xml

vmaas-go/go.mod, vmaas-go/go.sum
=> fix: update vmaas-lib

.github/workflows/tests.yml, Dockerfile, Pipfile, Pipfile.lock, docker-compose.test.listen.yml
=> chore: split github workflow steps in tests job

.github/workflows/safety.yml, .github/workflows/tests.yml, Dockerfile, poetry.lock, pyproject.toml, scripts/poetry-lock.sh, vmaas/reposcan/download/downloader.py, vmaas/webapp/app.py
=> chore: update python version

database/upgrade_scripts/018-csaf_tables.sql, database/vmaas_db_postgresql.sql
=> feat(csaf): add csaf_ tables needed to store csaf data

entrypoint.sh, vmaas/common/middlewares.py, vmaas/common/probes.py, vmaas/reposcan/reposcan.py, vmaas/webapp/app.py
=> fix uvicorn middlewares and logging

monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vmaas.configmap.yml, vmaas/common/middlewares.py, vmaas/reposcan/reposcan.py, vmaas/webapp/app.py
=> metrics fixes

poetry.lock, pyproject.toml
starlette, python-multipart, and cryptography
RHINENG-8390
connexion is upgraded so we can upgrade starlette
=> chore(deps): update vulnerable dependencies

vmaas-go/go.mod, vmaas-go/go.sum, vmaas-go/webapp/middlewares/ise.go
=> feat: update vmaas-lib

deploy/clowdapp.yaml, vmaas/common/config.py, vmaas/reposcan/redhatcsaf/csaf_controller.py, vmaas/reposcan/redhatcsaf/modeling.py, vmaas/reposcan/redhatcsaf/test/test_controller.py, vmaas/reposcan/redhatcsaf/test/test_modeling.py
=> fix(csaf): parse product status

.github/workflows/safety.yml
not running on PPC
using the lib only for checking expiration dates
=> chore: ignore CVE-2023-6129 as we're not affected

vmaas-go/go.mod, vmaas-go/go.sum
=> chore: update protobuf

vmaas/reposcan/redhatcsaf/csaf_controller.py
RHINENG-7868
needs to be merged before  #1086
=> fix(csaf): improve module parsing from csaf

vmaas-go/go.mod, vmaas-go/go.sum
=> feat(csaf): load csaf dump in webapp

vmaas/reposcan/dbdump.py, vmaas/reposcan/reposcan.py, vmaas/reposcan/reposcan.spec.yaml
=> fix(reposcan): add internal /download/pg_dump api

vmaas/reposcan/database/csaf_store.py, vmaas/reposcan/database/test/test_csaf.py
RHINENG-9510
```
Failed to populate cve: CVE-2023-28755 products: [CsafProduct(cpe='cpe:/o:redhat:enterprise_linux:6', package='ruby', status_id=4, module=None, id_=None, cpe_id=None, package_name_id=None, package_id=None), CsafProduct(cpe='cpe:/o:redhat:enterprise_linux:7', package='ruby', status_id=4, module=None, id_=None, cpe_id=None, package_name_id=None, package_id=None), CsafProduct(cpe='cpe:/o:redhat:enterprise_linux:8', package='ruby', status_id=4, module='ruby:2.6', id_=None, cpe_id=None, package_name_id=None, package_id=None), CsafProduct(cpe='cpe:/o:redhat:enterprise_linux:8', package='ruby', status_id=4, module='ruby:3.0', id_=None, cpe_id=None, package_name_id=None, package_id=None), CsafProduct(cpe='cpe:/o:redhat:enterprise_linux:9', package='ruby', status_id=4, …
```
=> fix(csaf): populate mapping with updated files

vmaas/reposcan/database/csaf_store.py, vmaas/reposcan/database/test/test_csaf.py
=> fix(csaf): query argument

vmaas-go/go.mod, vmaas-go/go.sum
RHINENG-7869
depends on https://github.com/RedHatInsights/vmaas-lib/pull/52
=> feat(csaf): use csaf in /vulnerabilities

vmaas-go/go.mod, vmaas-go/go.sum
=> fix: update vmaas-lib to improve concurrency

vmaas/reposcan/database/csaf_store.py, vmaas/reposcan/redhatcsaf/test/test_controller.py
RHINENG-9586
~16k files is synced with every sync because they don't contain any unfixed products and are skipped
=> fix(csaf): update file timestamp for skipped cve

vmaas/reposcan/database/csaf_store.py, vmaas/reposcan/database/test/test_csaf.py
=> fix(csaf): remove products if they become fixed/unaffected

vmaas-go/go.mod, vmaas-go/go.sum
=> fix(csaf): cves for source packages

database/upgrade_scripts/021-csaf_errata.sql, database/vmaas_db_postgresql.sql, deploy/clowdapp.yaml, vmaas/common/config.py, vmaas/reposcan/conftest.py, vmaas/reposcan/database/csaf_store.py, vmaas/reposcan/exporter.py, vmaas/reposcan/redhatcsaf/csaf_controller.py, vmaas/reposcan/redhatcsaf/modeling.py, vmaas/reposcan/redhatcsaf/test/cve-2023-1017.json, vmaas/reposcan/redhatcsaf/test/test_modeling.py
=> feat(csaf): parse and store fixed csaf vex products 

.github/workflows/safety.yml, Dockerfile, docker-compose.test.yml, docker-compose.yml
=> chore: Centos 8 Stream was removed, install postgresql and rpm-devel from COPR

vmaas/common/logging_utils.py
=> fix: include levelname in CW logs from python code

database/upgrade_scripts/022-csaf-fixed-package-name.sql, database/vmaas_db_postgresql.sql, vmaas/reposcan/database/csaf_store.py, vmaas/reposcan/database/test/test_csaf.py
=> fix: store package_name_id for fixed csaf_product

conf/reposcan.env, deploy/clowdapp.yaml, vmaas/reposcan/redhatoval/oval_controller.py
=> chore(reposcan): add OVAL_SYNC_ALL_FILES flag

security-scan.sh
Adding the Security Scanning Workflow. This script will provide the same level of support as the standard PlatSec GitHub Workflow.
A copy of the [security-scan-source-template.sh](https://github.com/RedHatInsights/platform-security-gh-workflow/blob/master/jenkins/security-scan-source-template.sh) has been added to this repo, and the (GitHub) `platsec-gh-vulnerability-scan` Jenkins Job has be added to the VMAAS `build.yml` in App-Interface.
Similar to the standard GitHub Workflow, we can accommodate feature requests and provide updates on the fly and with full transparency. The `security-scan-source-template.sh` script, which sources the main [security-scan.sh](https://github.com/RedHatInsights/platform-security-gh-workflow/blob/master/jenkins/security-scan.sh) script, allows us to support …
=> Adding Security-Scan Script to Enable Jenkins Security Scan Job

vmaas-go/go.mod, vmaas-go/go.sum, vmaas/reposcan/redhatoval/definitions_file.py
=> fix(reposcan): exclude under investigation CVEs from OVAL

vmaas/reposcan/database/test/test_csaf.py, vmaas/reposcan/redhatcsaf/csaf_controller.py, vmaas/reposcan/redhatcsaf/modeling.py, vmaas/reposcan/redhatcsaf/test/test_modeling.py
=> fix(csaf): download only files from csv

vmaas-go/go.mod, vmaas-go/go.sum
=> RHINENG-10310: manually_fixable_cves from csaf

vmaas/common/logging_utils.py
=> fix: string formatting in CloudWatch

deploy/clowdapp.yaml
=> chore: increase webapp memory request/limit

vmaas-go/go.mod, vmaas-go/go.sum
=> fix: match cpe pattern substrings

vmaas-go/go.mod, vmaas-go/go.sum
=> feat(webapp-go): report module info for unfixed CVEs

vmaas-go/go.mod, vmaas-go/go.sum
=> fix: detect all affected packages for unfixed vulns

deploy/clowdapp.yaml
=> fix: stop using beta vex files

poetry.lock
=> fix: update dependencies

README.md, conf/cdappconfig.json, conf/common.env, deploy/clowdapp.yaml, docker-compose.yml, vmaas-go/go.mod, vmaas-go/go.sum, vmaas-go/webapp/webapp.go, vmaas/common/config.py, vmaas/reposcan/reposcan.py, vmaas/reposcan/reposcan.spec.yaml
=> fix: add internal endpoint for profiling webapp-go

vmaas/reposcan/conftest.py, vmaas/reposcan/redhatcsaf/csaf_controller.py, vmaas/reposcan/redhatcsaf/test/cve-2023-0049.json, vmaas/reposcan/redhatcsaf/test/cve-2023-1017.json
=> fix(csaf): module parsing

database/upgrade_scripts/023-csaf-fixed-indexes.sql, database/vmaas_db_postgresql.sql
package_name_id is always stored (RHINENG-10310)
RHINENG-11156
=> fix(csaf): update indexes for fixed products

vmaas/reposcan/reposcan.py
use 20s profile instead of default 30s, 3scale timeout in stage/prod is 30s and profile would result in gateway timeout
=> chore(pprof): profile cpu for 20s

vmaas-go/go.mod, vmaas-go/go.sum
=> fix(csaf): fixed products with moduels

.github/workflows/lint.yml, .github/workflows/tests.yml
=> chore: update gh actions

vmaas-go/go.mod, vmaas-go/go.sum
https://github.com/RedHatInsights/vmaas-lib/pull/66
RHINENG-12093
=> feat(csaf): exclude kernel-alt from evaluation

vmaas-go/go.mod, vmaas-go/go.sum
=> fix(csaf): duplicate cpes while processing

.github/workflows/tests.yml, Dockerfile, deploy/clowdapp.yaml, docker-compose.test.yml, docker-compose.yml, entrypoint.sh, scripts/poetry-lock.sh
=> chore: use ubi9

vmaas-go/go.mod, vmaas-go/go.sum
=> feat(webapp-go): get newer EUS manually fixable from repos

renovate.json
=> chore: try to automerge updating tekton references

vmaas-go/go.mod, vmaas-go/go.sum
=> fix(webapp-go): duplicate affected packages and incorrect manually fixable errata

vmaas-go/go.mod, vmaas-go/go.sum
=> fix(vmaas-go): revert appendUniq due to performance hit

pyproject.toml
going to enable Konflux image build only for tags
=> ci: create patch tag for more keywords

deploy/clowdapp.yaml, vmaas-go/base/core/config.go, vmaas-go/base/utils/config.go, vmaas-go/go.mod, vmaas-go/go.sum, vmaas-go/webapp/controllers/utils_test.go, vmaas-go/webapp/controllers/vulnerabilities.go
=> feat: env var for newer releasever, remove use_csaf

Dockerfile, deploy/clowdapp.yaml, docker-compose-dbdocs.yml, docker-compose.test.yml, docker-compose.yml
=> chore: upgrade db to pg 16

vmaas/reposcan/reposcan.spec.yaml
=> chore: intenral api to upload dump to s3

Dockerfile
=> chore: revert to ubi8

vmaas/webapp/repos.py
=> fix(webapp): label key is not in result dict if all repos are skipped

vmaas/common/config.py
=> fix(s3): get accessKey from bucket not objectStore

.tekton/vmaas-pull-request.yaml, .tekton/vmaas-push.yaml
=> ci: add new mandatory RPM signature scan task to tekton

vmaas-go/go.mod, vmaas-go/go.sum
=> fix: ignore updates from rhel-alt el7a release

vmaas-go/go.mod, vmaas-go/go.sum
=> fix: false positives for kernel-rt source package

Dockerfile, vmaas/reposcan/database/release_store.py, vmaas/reposcan/redhatrelease/gen_package_profile.py, vmaas/reposcan/redhatrelease/modeling.py, vmaas/reposcan/redhatrelease/release_controller.py
=> feat(reposcan): generate system profile for each RHEL release

database/upgrade_scripts/026-operating_system_sp_nn.sql, database/vmaas_db_postgresql.sql, vmaas/reposcan/exporter.py
=> fix(reposcan): system_profile column should now be always NOT NULL

vmaas-go/go.mod, vmaas-go/go.sum, vmaas-go/webapp/controllers/os.go, vmaas-go/webapp/routes/routes.go
=> feat(vmaas-go): OS Release Vulnerability Report API

Dockerfile
=> chore: use ubi9 image

vmaas/common/logging_utils.py
=> fix: log with 'message' attribute instead of 'msg'

vmaas/reposcan/database/csaf_store.py, vmaas/reposcan/database/test/test_csaf.py, vmaas/reposcan/redhatcsaf/csaf_controller.py
=> fix: delete removed csaf files from db

deploy/clowdapp.yaml, vmaas-go/base/utils/config.go, vmaas-go/go.mod, vmaas-go/go.sum, vmaas-go/webapp/controllers/pkglist.go, vmaas-go/webapp/routes/routes.go
=> feat(webapp): add go controller for pkglist endpoint

vmaas-go/go.mod, vmaas-go/go.sum
=> feat: newer release cves not fixed in current release

vmaas-go/go.mod, vmaas-go/go.sum
=> fix: update vmaas-lib to fix /repos

vmaas-go/go.mod, vmaas-go/go.sum
=> feat(webapp-go): add lifecycle_phase to the response

deploy/clowdapp.yaml, vmaas-go/base/utils/config.go, vmaas-go/webapp/controllers/pkgtree.go, vmaas-go/webapp/routes/routes.go
=> feat(webapp): add go controller for pkgtree endpoints

deploy/clowdapp.yaml, vmaas-go/base/utils/config.go, vmaas-go/go.mod, vmaas-go/go.sum, vmaas-go/webapp/controllers/patches.go, vmaas-go/webapp/routes/routes.go
=> feat(webapp): add go controllers for patches endpoints

renovate.json
=> improve renovate behavior

deploy/clowdapp.yaml, vmaas-go/base/utils/config.go, vmaas-go/go.mod, vmaas-go/go.sum, vmaas-go/webapp/controllers/package_names.go, vmaas-go/webapp/routes/routes.go
=> feat(webapp): add go controller for package_name/rpms endpoints

deploy/clowdapp.yaml, vmaas-go/base/utils/config.go, vmaas-go/go.mod, vmaas-go/go.sum, vmaas-go/webapp/controllers/package_names.go, vmaas-go/webapp/routes/routes.go
=> feat(webapp): add go controller for package_name/srpms endpoints

vmaas/reposcan/reposcan.py
=> fix(reposcan): skip if token is not set

poetry.lock
=> chore: update h11 dependency

vmaas/webapp/app.py, vmaas/webapp/webapp.v3.spec.yaml
=> chore(webapp): Update v3 spec yaml to have os report

.github/workflows/tests.yml, Dockerfile, docker-compose.test.listen.yml, docker-compose.test.yml
=> chore: optimize image size by building python deps in build phase
