RedHatInsights/vmaas

database/vmaas_db_postgresql.sql

When syncing e.g. EPEL 7 repository I found out 4000 characters for synopsis in errata table is not enough again. Is there any reason to not simply use the TEXT type without limiting the length?

use TEXT types instead of VARCHAR

---

database/vmaas_db_postgresql.sql

Even if the current errata evaluation algorithm doesn't need information from this table, it's needed to track this reference.
For example, text-only errata need to store this reference into DB to know where they came from.
It'll allow to simply list repositories or products containing given erratum without selecting over packages.

add table errata_repo

---

reposcan/database/update_store.py
reposcan/repodata/updateinfo.py

1. Variable name updated should be called issued (this change has no effect on functionality)
2. Description field can be undefined sometimes (https://access.redhat.com/errata/RHEA-2003:018)
2. Make sure CVE-erratum associations are not duplicated in insert query (https://access.redhat.com/errata/RHSA-2005:802).

Fixing various issues in updateinfo parsing/importing

---

reposcan/repodata/primary.py
reposcan/repodata/repomd.py
reposcan/repodata/updateinfo.py

e.g. updateinfo in /content/dist/rhel/rhui/server/6/6Server/x86_64/rhscl/1/os repository contains trailing whitespaces
fixing #28, example:
```
<tag>text inside
</tag>
```
will be parsed as "text inside", without the newline.

make sure all texts inside XML elements are stripped

---

reposcan/dummy_crawler.sh

Just add a workaround for the workaround :) 
dummy_crawler is our temporary solution to crawl through a list of repositories and collect repodata. In the future versions, we are going to use a real crawler which will be triggered by service. For now, I added the infinite loop to the dummy_crawler just to keep container running.

run dummy_crawler in infinite loop.

---

reposcan/common/batch_list.py
reposcan/database/repository_store.py
reposcan/repodata/repository.py
reposcan/repodata/repository_controller.py

1. Use stored revision timestamp from DB to filter out not updated repositories.
2. Optimize downloading in batches - download all repomd files first at once (their disk space usage is marginal) and then sort out into batches only passed repositories, it helps in case when for example 10000 repomd files are downloaded but only 5 of them needs update, this way these 5 repositories can be processed in single batch.
3. Refactoring, put these two functions inside repository class as it makes better sense.
4. Add more log messages.

Filter repositories based on timestamp + some fixes

---

database/vmaas_db_postgresql.sql

This table is not filled with data yet. Add INT column to store engineering product ID here.
Example:
eng_product_id: 69
name: "Red Hat Enterprise Linux Server"

add product ID column

---

docker-compose.yaml

Downloaded and decompressed repodata can be too big for application container in OpenShift, store them in a dedicated storage.

save downloaded files outside the application container

---

webapp/updates.py

Some updates could be w/o erratum associated. In this case, we should skip exactly this update package and do not stop processing other updates

api: updates: skip only updates w/o erratum associated.

---

webapp/database.py

This fixes the issue where an error during a database query results in no more ability to talk to the database.

Issue 67 - set connection to readonly and autocommit

---

webapp/Dockerfile
webapp/app.py
webapp/repos.py
webapp/updates.py
webapp/vmaas

Since we are not using ujson anymore, 'epel' reposotory is also removed.
Removed some unused imports:
'import os' in webapp/app.py
'import sys' in webapp/repos.py

api: use python json module from the standard library, instead of ujson from epel

---

webapp/app.py

This doc handler was used for debug purpose only and now outdated.
We are not going to support documentation in this place.

api: remove outdated doc handler.

---

webapp/updates.py

example:
curl -X GET http://127.0.0.1:8080/api/v1/updates/kernel-2.6.32-696.18.7.el6.x87_74
```
vmaas-webapp | ERROR:tornado.application:Uncaught exception GET /api/v1/updates/kernel-2.6.32-696.18.7.el6.x87_74 (172.18.0.1)
vmaas-webapp | HTTPServerRequest(protocol='http', host='127.0.0.1:8080', method='GET', uri='/api/v1/updates/kernel-2.6.32-696.18.7.el6.x87_74', version='HTTP/1.1', remote_ip='172.18.0.1', headers={'Host': '127.0.0.1:8080', 'Accept': '*/*', 'User-Agent': 'curl/7.55.1'})
vmaas-webapp | Traceback (most recent call last):
vmaas-webapp |   File "/usr/lib64/python2.7/site-packages/tornado/web.py", line 1412, in _execute
vmaas-webapp |     result = method(*self.path_args, **self.path_kwargs)
vmaas-webapp |   File "/app/app.py", line 27, in get
vmaas-webapp |     response = …
```

fix input package with invalid architecture

---

webapp/errata.py

This fixes a bug introduced in PR #143 which caused the errata API to stop returning results - 'mydict' attribute was renamed to 'data' in one place but not another.
This also removes unnecessary get_val() method.

fix errata api bug introduced in pr143

---

docker-compose.yml

to propagate into openshift deployment config when processed by kompose tool

specify internal port number in docker-compose config

---

database/vmaas_db_postgresql.sql
reposcan/database/update_store.py
webapp/errata.py

This finishes Issue #119.
It also reworks how the various lists of info in an erratum are retrieved - it makes 3 db queries to populate lists in all errata instead of 3 db queries per erratum.

Add more errata data

---

database/vmaas_db_postgresql.sql
reposcan/common/utc.py
reposcan/database/cve_store.py
reposcan/database/repository_store.py
reposcan/repodata/repomd.py
reposcan/repodata/repository_controller.py
reposcan/repodata/test/test_repomd.py
reposcan/repodata/updateinfo.py
webapp/cve.py
webapp/errata.py
webapp/repos.py
webapp/utils.py

fixes #116 
- all timestamps in DB to use timezones
- enhance repo API to return revision
- import all timestamps (from repodata, CVE lists) as UTC timestamps regardless of DB timezone
- output format in ISO 8601

improve timestamp handling

---

webapp/cve.py

was (wrong):
```
{
"CVE-1234": {...}
...
}
```
should be (corrrect):
```
{
"cve_list": {
"CVE-1234": {...}
...
}
}

fixed format of /cve response

---

.gitignore
.travis.yml
docker-compose.yml
libs/python-apispec/python-apispec.spec
reposcan/Dockerfile
reposcan/reposcan.py
webapp/Dockerfile
webapp/app.py

This PR adds automatically generated API documentation (based on Python docstrings) visualized in Swagger UI (new service in docker-compose on port 8000).
Swagger UI is set up to visualize both webapp and reposcan APIs - Swagger UI fetches and displays JSON from newly added `/api/v1/apispec` APIs in both webapp and reposcan.
This JSON is in OpenAPI format and I used `apispec` Python library to generate it. Unfortunately, this library is not available in RHEL/CentOS/Fedora repositories (I was not able to find any similar library even) but I was able to build it in Copr using attached specfile (in jdobes/vmaas-libs repo, let's change it later).
TODO:
- add input and output JSON examples for each API
- find a way how to deploy in Openshift without manual config changes

Interactive Swagger UI API doc

---

webapp/app.py
webapp/database.py
webapp/errata.py

This PR addresses Issue #120 for the errata api - it gets rid of the need to disable pylint warnings for too-many-arguments and too-many-local-variables.
This also changes errata api to use RealDictCursor from the psychopg2.extras package. This allows us to use the dictionaries returned directly from the sql queries in the api response. Take a look and see if we want to apply this across all APIs as it may be a slight performance increase in addition to removing the need to disable pylint warnings for too-many-arguments and too-many-local-variables.

120 - Refactor to prevent pylint warnings in errata api (use RealDictCursor)

---

reposcan/database/cve_store.py

This will get impact/severity from baseMetricV2 if baseMetricV3 does not exist.  Let's make sure this is what we want before merging this PR.
Also, this PR will conflict with PR #214.  PR #214 should be merged first, then I'll fix this one.

Fix #206 - get impact/severity from baseMetricV2 if V3 doesn't exist

---

reposcan/database/update_store.py
reposcan/repodata/repomd.py
reposcan/repodata/test/test_repomd.py
reposcan/repodata/updateinfo.py
scripts/list_rhsm_repos.py

```
$ ./scripts/list_rhsm_repos.py -h
usage: list_rhsm_repos.py [-h] [-l] [--show-content-sets] [--include-no-skus]
[--include-sources] [-i INCLUDE_PRODUCTS]
[-e EXCLUDE_PRODUCTS] [--rhsm-cert RHSM_CERT]
[--rhsm-key RHSM_KEY] [--cdn-url CDN_URL]
optional arguments:
-h, --help            show this help message and exit
-l, --list-products   List active engineering products in console.
--show-content-sets   Show content sets provided by products. Use only with
-l.
--include-no-skus     Include products without SKUs in output.
--include-sources     Include source content sets in output.
-i INCLUDE_PRODUCTS, --include-products INCLUDE_PRODUCTS
Include product IDs only.
-e EXCLUDE_PRODUCTS, --exclude-products EXCLUDE_PRODUCTS
Exclude product IDs.
--rhsm-cert RHSM_CERT
Path to RHSM client …
```

add script listing RHSM repositories and fix some bugs in code

---

database/vmaas_db_postgresql.sql
webapp/app.py
webapp/dbchange.py

- Adds 'dbchange' table to schema to track errata/cve/repos/any most-recent-change
- Adds initial-insert to guarantee dbcnage starts out with 'time db was created'
- Adds functions to db to update the columns in dbchange
- Adds triggers to various tables to call the appropriate function, depending on
which entity is changed
- adds webapp/dbchange.py to expose the API /api/v1/dbchange
- adds APISpec doc for same

Add API to return last DB change

---

webapp/app.py
webapp/database.py
webapp/updates.py
webapp/utils.py

Rewrite /updates API to not use database directly but to use precached data on webapp start. With 14000 repositories it takes 800 MB in memory. Using my sample request with 950 package NEVRAs it seems 25 times faster than before.
Note: In output JSON packages without security updates no longer have summary and description fields filled because such packages are not in cache.

rewrite /updates API to use cached data only

---

webapp/Dockerfile

Error: [Errno 14] HTTPS Error 404 - Not Found
ERROR: Service 'webapp' failed to build: The command '/bin/sh -c yum -y update     && yum -y install yum-plugin-copr     && yum -y copr enable @vmaas/libs     && yum -y install epel-release     && yum -y install python-tornado python-psycopg2 python2-apispec postgresql python-dateutil python2-futures python2-jsonschema     && rm -rf /var/cache/yum/*' returned a non-zero code: 1

workaround broken yum/copr plug-in on el7

---

docker-compose.yml
reposcan/Dockerfile
reposcan/database/database_handler.py
reposcan/exporter.py
reposcan/reposcan.py
webapp/Dockerfile
webapp/app.py
webapp/cache.py
webapp/cve.py
webapp/errata.py
webapp/updates.py

Disk dump of data allows us to separate master database from webapps and possibly add  on-premise/disconnected features.

Rewrite /updates to use disk dump instead of connect to database

---

reposcan/rsyncd.conf
webapp/cache.py

containers in openshift run as non-root so they can't open port < 1024

modify rsync to run in openshift

---

webapp/updates.py

A single package nevra can be released into different repositories
by different errata. When looping by repositories, we confused this
issue, resulting in being able to show erratum for repositories they
didn't belong to.
Swicthed the loop-nesting, so that we now build /updates by-erratum,
instead of by-repository.

Fix #273 - Build updates-response per-erratum instead of per-repo

---

reposcan/exporter.py
webapp/app.py
webapp/cache.py
webapp/errata.py

I have cut-n-pasted the join_packagename() method from webapp/utils.py to reposcan/common/package_utils.py.  I'll open an issue that this should possibly be move to a utils or lib that gets used by both webapp and reposcan.

Make errata api use Phase II design

---

webapp/updates.py

INPUT:
```javascript
{
"repository_list": [
"rhel-7-server-rpms"
],
"releasever": "7Server",
"basearch": "x86_64",
"package_list": [
"dconf-0.26.0-2.el7.x86_64"
]
}
```
OUTPUT:
```javascript
{
"update_list": {
"dconf-0.26.0-2.el7.x86_64": {
"summary": "A configuration system",
"description": "dconf is a low-level configuration system. Its main purpose is to provide a\nbackend to the GSettings API in GLib.",
"available_updates": [
]
}
},
"repository_list": [
"rhel-7-server-rpms"
],
"releasever": "7Server",
"basearch": "x86_64"
}
```

#301 api: updates: if all packages are in the hot cache already, we need to fill a response with the input repo information anyway.

---

webapp/cache.py

Fixes an issue on webapp
vmaas-webapp | rsync: symlink "/data/vmaas.dbm" -> "/data/vmaas.dbm-2018-06-18T08:31:32.670869+00:00" failed: File exists (17)
vmaas-webapp | rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1659) [generator=3.1.3]

copy the data behind the symlink not link itself

---

webapp/utils.py

when format_datetime received None it converted into string "None"
which was confusing for subsequent calls with returned value
which were doing tests for None as "None" is None == False

fix #320 - don't convert None into string, just return None

---

reposcan/reposcan.py

1. We also discussed a possibility to set an environment variable to check is it necessary to authorize a user or not. I'm not sure we need it right now and I can add it later.
2. Github personal access token can have specified permissions. For the authorization, we require only permissions `read:user`

reposcan: introduce authentication for the management API.

---

docker-compose.yml

min and max resources for containers:
database - 0.2 up to 1.0 CPU, 200M up to 1G memory
reposcan - 0.2 up to 1.0 CPU, 200M up to 1G memory
webapp - 0.2 up to 1.0 CPU, 2G memory
apidoc - 0.1 CPU, 100M memory

define requirements for services

---

docker-compose.yml

this is a workaround, not a fix
to fix it it's necessary to fix #26 and correctly handle child process status when this crash happens (this causing a bug as kernel kills python worker subprocess and nothing is returned back to main python process - reposcan is stuck)

reposcan can occasionally take more memory and crash silently

---

reposcan/pkgtree.py

Fix pkgtree export when repo.basearch_id is null

---

apidoc/Dockerfile

API_URLS env variable was both defined in Dockerfile and conf/apidoc.env

remove duplicated env variable setting

---

reposcan/exporter.py
webapp/app.py
webapp/cache.py
webapp/updates.py

This PR addresses modularity updates and modular erratas.
There's a new parameter added to the POST /updates API called modules_list (see SwaggerUI), which serves as constraint to the updates search.
Without "modules_list" the /updates API returns every possible update, with no regards to enabled modules (it will offer package from other stream as an update if it has higher NEVRA).
With "modules_list" parameter present, but empty, the /updates API expects that no modules are enabled and will discard all modular erratas.
When "modules_list" is present and NOT empty, /updates API will show modular updates coming only from modules in the "modules_list" and all non-modular updates as well.

process modular updates

---

reposcan/database/modules_store.py
reposcan/database/update_store.py

Erratas may introduce new version of module when the version or context changes. Store these different N:S:V:Cs into database.

store new module versions introduced by erratas into database

---

Dockerfile-reposcan
Dockerfile-reposcan.rhel7
reposcan/apidoc.py
reposcan/download/downloader.py
reposcan/mnm.py
reposcan/nistcve/cve_controller.py
reposcan/redhatcve/cvemap_controller.py
reposcan/repodata/repository_controller.py
reposcan/reposcan.py
webapp/app.py

This adds the basic framework to reposcan. However, the majority of
the work reposcan does happens in async children, which are separate
processes from the parent; their counts do not make it up to
MetricsHandler. A future task needs to teach reposcan's controllers
how to export their info.

VMAAS-328 - Add more monitoring to vmaas

---

webapp/updates.py

vmaas-webapp       | f44bdb3ffc28 2019-04-04 08:13:25,084 __main__: [ERROR] Internal server error <-9223363243124068951>: please include this error id in bug report.'Traceback (most recent call last):\n  File "/webapp/app.py", line 105, in handle_post\n    res = api_endpoint.process_list(api_version, data)\n  File "/webapp/updates.py", line 381, in process_list\n    module_info = [(x[\'module_name\'], x[\'module_stream\']) for x in modules_list]\n  File "/webapp/updates.py", line 381, in <listcomp>\n    module_info = [(x[\'module_name\'], x[\'module_stream\']) for x in modules_list]\nKeyError: \'module_stream\''|
vmaas-webapp       | f44bdb3ffc28 2019-04-04 08:13:25,084 __main__: [INFO] Input data for <-9223363243124068951>: {'package_list': …

catch missing parts of module info during json schema validation

---

Dockerfile-reposcan
Dockerfile-reposcan.rhel7
Dockerfile-webapp
Dockerfile-webapp-qe
Dockerfile-webapp.rhel7
Dockerfile-websocket
Dockerfile-websocket.rhel7
run_tests.sh

Previously we were adding our code before running e.g. pip install or other things which are changing less often and have bigger layers than our code.
I've restructured the Dockerfiles in a way that things that are changing the least and take the biggest amount of time are run first, and our code is added at last possible place so we won't run whole `pip install --upgrade && pip install $LOT_OF_STUFF` after one line of code gets changed.

 reduce number of intermediate Docker images after code change 

---

webapp/app.py
webapp/test/test_vulnerabilities.py
webapp/vulnerabilities.py

by instantiating a new object each call all caching was made useles as after one API call the cached things were garbage collected

don't instantiate new UpdatesAPI each call

---

database/vmaas_db_postgresql.sql
reposcan/database/modules_store.py
reposcan/database/object_store.py
reposcan/database/package_store.py
reposcan/repodata/primary.py
reposcan/repodata/primary_db.py
reposcan/repodata/test/test_primary.py
reposcan/test_data/exporter/exporter_test_data.sql
webapp/updates.py

- currently single package NEVRA can be stored in package table multiple times when it's available from different repos - based on checksum used in each repo (some use sha1, some sha256)
- however vmaas doesn't expose checksum anywhere, neither vmaas works with binary packages, I think we can safely remove package checksums
- each NEVRA will be unique in package table

get rid of package checksum

---

webapp/test/test_updates.py
webapp/test/test_utils.py
webapp/updates.py

fixes
Traceback (most recent call last):\n  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/tornado/gen.py", line 191, in wrapper\n    result = func(*args, **kwargs)\n  File "/webapp/app.py", line 130, in handle_get\n    result = api_endpoint.process_list(api_version, {param_name : [param]})\n  File "/webapp/vulnerabilities.py", line 17, in process_list\n    updates = self.updates_api.process_list(2, data)\n  File "/webapp/updates.py", line 435, in process_list\n    available_repo_ids, repo_ids_key, response, module_ids)\n  File "/webapp/updates.py", line 337, in _process_updates\n    nevra = self._build_nevra(update_pkg_id)\n  File "/webapp/updates.py", line 271, in _build_nevra\n    name_id, evr_id, arch_id, _, _ = …

source_package_id needs to be extracted

---

reposcan/database/package_store.py

fixing
> [ERROR] Internal server error <-9223363302935117324>'Traceback (most recent call last):\n  File "/reposcan/reposcan.py", line 661, in run_task\n    repository_controller.store()\n  File "/reposcan/repodata/repository_controller.py", line 264, in store\n    self.repo_store.store(repository)\n  File "/reposcan/database/repository_store.py", line 167, in store\n    self.package_store.store(repo_id, repository.list_packages())\n  File "/reposcan/database/package_store.py", line 169, in store\n    source_packages = self._get_source_packages(packages)\n  File "/reposcan/database/package_store.py", line 158, in _get_source_packages\n    unique_source_packages.add(PackageStore._get_source_package_nevra(pkg))\n  File "/reposcan/database/package_store.py", line 80, in …

fix getting srpm from source packages

---

database/vmaas_db_postgresql.sql

functions were used in previously removed sql function 'rpmver_array'
now they are useless so they are removed

removed useless sql functions 'isdigit', 'isalpha', 'isalphanum'

---

Jenkinsfile

Now, when it is not executed using scl-enable.sh, --omit path should not be in quotes.

correct omitting of /opt in Jenkinsfile

---

Jenkinsfile

Use Lockable Resource Plugin to lock openshift vmaas-qe project resource while tests are running.

Jenkins - disable concurrent builds

---

webapp/repos.py
webapp/test/test_repos.py

`curl -X POST -d '{"repository_list": ["rhel-7-server-rpms"]}' localhost:8080/api/v1/repos/ | python -m json.tool`
```{
"page": 1,
"page_size": 2,
"pages": 1,
"repository_list": {
"rhel-7-server-rpms": [
{
"basearch": "x86_64",
"label": "rhel-7-server-rpms",
"name": "Red Hat Enterprise Linux 7 Server (RPMs)",
"product": "Red Hat Enterprise Linux Server",
"releasever": "7.4",
"revision": "None",
"url": "https://cdn.redhat.com/content/dist/rhel/server/7/7.4/x86_64/os/"
},
{
"basearch": "x86_64",
"label": "rhel-7-server-rpms",
"name": "Red Hat Enterprise Linux 7 Server (RPMs)",
"product": "Red Hat Enterprise Linux Server",
"releasever": "7Server",
"revision": "2018-04-10T09:02:26+00:00",
"url": "http://vmaas-data-vmaas-qe.5a9f.insights-dev.openshiftapps.com/repodata-for-vmaas/rhel/server/7/7S …
```

/repos API + modified_since wrong and inconsistent results

---

reposcan/repodata/repomd.py
reposcan/repodata/repository_controller.py
reposcan/repodata/test/test_repomd.py

This fixes bug introduced by #578, which resulted in sync error when `repomd.xml` entries did not have size.

Accept repomd entries without size

---

reposcan/database/repository_store.py
reposcan/database/update_store.py
webapp/cve.py
webapp/test/test_utils.py
webapp/test/tools.py
webapp/test/yaml_cache.py
webapp/updates.py

Profiling revealed the `process_list` method spent ~ 60% of its time in `_get_repositories`. Reduced unnecessary loops and optimized the order of conditions. This commit results in the `/vulnerabilities` endpoint being able to process ~ 20% more requests per second on synthetic tests.

Optimize _get_repositories method in updates API

---

webapp/app.py

This unifies the way metrics are reported between reposcan and webapp. Previously, the webapp returned metrics as `Content-Type: application/octet-stream` while reposcan uses `Content-Type: text/plain`

Provide webapp metrics as text/plain

---

webapp/app.py
webapp/test/test_app.py
webapp/webapp.spec.yaml

Now the errors should look exactly like the ones from vulnerability engine.
The webapp spec was edited to match the jsons exactly inside ```.py``` files, so that the validation error gets done only by connexion, so that the new middleware ```error_formater``` would work properly.

Add error formatter and edit webapp spec

---

webapp/app.py

- Fix 500 when vmaas returned errors that were not made by connexion e.g. wrong regular expression

Fix 500 in error_formater

---

Jenkinsfile

There is a new feature in insights-pipeline-lib that changes functionality of `openshift.withNode`, we can pin insights-pipeline-lib to v1.3 for now and do the necessary changes later

pin insights-pipeline-lib version

---

webapp/app.py

- Change of the response for wrong request helps the error_formater to easily parse the error

Fix 500 when request not json

---

reposcan/exporter.py
reposcan/reposcan.py
reposcan/test/test_exporter.py
webapp/cache.py
webapp/packages.py
webapp/test/data/cache.yml
webapp/test/test_cache.py
webapp/updates.py

- Store list[int] as raw long arrays, reduces memory usage by ~300 MB for production database.
- Deduplicate strings from package details and also store package_details as array , saves additional ~200 MB.

Memory optimizations

---

.travis.yml
Dockerfile.dbdocs
docker-compose-dbdocs.yml
scripts/db_docs_generator.sh
scripts/schemaspy.properties

The database generation script, is always executed at the start of travis run, the db docs are generated based on the checksum change of the schema sql script. Docs are pushed into [docs repo](https://github.com/RedHatInsights/vulnerability-docs). Docs are generated only for commits into master or stable.

Add database generation script and settings

---

Jenkinsfile

This should free up some slots on Jenkins master executor. Since we run with nested node calls like this:
```
node {
openShiftUtils.withNode {
lock
}
}
```
If the job is waiting on a log, the executor on the master node gets held up for the duration of the job run. A node is not required to run `cancelPriorBuilds`.

Do not allocate node until stages start running

---

Pipfile
conf/reposcan.env
openshift/secrets.yml
openshift/vmaas-reposcan.yml
reposcan/Dockerfile
reposcan/Dockerfile.rhel7
reposcan/Pipfile
reposcan/Pipfile.lock
reposcan/download/downloader.py
reposcan/repodata/repository_controller.py
reposcan/reposcan.py
reposcan/reposcan.spec.yaml

This PR adds a new SyncTask, which downloads repolist from github and imports it into database.
Before merging we have to figure out whether we want to create a new Openshift secret , or use existing `github-vulnerability-bot` secret for authorization against private repository.

Allow downloading repolist from git

---

Jenkinsfile

Without slash it runs also vulnerability tests because of jenkins workspace path @jdobes was too fast and merged it before my force push :smile:

chore: jenkinsfile path to tests

---

Jenkinsfile
webapp/Dockerfile-qe

fixes coverage measurements after switching to UBI images

chore: ignore coverage of python modules in /usr

---

.github/workflows/main.yml
Jenkinsfile
conf/repolist.json
scripts/setup_db.sh

Use github actions instead of Jenkins for PR testing with integration tests. It builds docker-compose locally and executes vmaas tests from image with all iqe plugins installed.
Runs on every `push` event, even in your fork. It doesn't have to wait for previous deployment as Jenkins, but it needs some configuration for everyone who wants to make a PR.
__Needed configuration:__
- Set Secrets under Settings of your repository (fork).  Ping me (or I can send an e-mail) for values of following secrets
- IQE_TESTS_IMAGE
- REGISTRY_PASSWORD
- REGISTRY_USERNAME
- REPOLIST_JSON

chore: use github actions for integration tests

---

Jenkinsfile

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 53: expecting anything but ''\n''; got it anyway @ line 53, column 62.
oy -f --sets vmaas -e vmaas-qe

chore: jenkinsfile line continuation

---

Pipfile
Pipfile.lock
reposcan/Pipfile
reposcan/Pipfile.lock
webapp/Pipfile
webapp/Pipfile.lock
webapp/app.py
webapp/test/test_app.py
webapp_utils/Pipfile
webapp_utils/Pipfile.lock

The old connexion version is causing a problem when we need to upgrade packages through Pipfile.
[Source](https://github.com/zalando/connexion/issues/1149)

chore: upgrade connexion version

---

webapp/app.py
webapp/test/test_app.py

The error formatter provided by connexion is not good at handling exceptions so I again created lighter version of error formatter. Also, I created a test so that the exceptions error formatter is tested in unit test and not only in integration tests.

feat(webapp): add lite error formatter

---

openshift/secrets.yml
openshift/vmaas-webapp.yml

- The HPA works with resource requests, not limits, so up the request to 0.5 of a core,
and make the autoscaler to keep the utilization on this value.
The autoscaler should add more pods when average utilization is > 0.5

Add autoscaler to webapp, format secrets as a list of yaml values

---

Dockerfile.test
database/README.md
database/upgrade/dbupgrade.sh
database/upgrade_scripts/000-dbupgrades.sql
database/vmaas_db_postgresql.sql
reposcan/Dockerfile
reposcan/database/database_handler.py
reposcan/database/test/conftest.py
reposcan/database/test/test_upgrade.py
reposcan/database/test/test_upgrader.py
reposcan/database/test/test_upgrades.py
reposcan/database/upgrade.py

Basically, the process is the same like for vulnerability-engine.
- The database upgrade scripts are placed into ```/database/upgrade_scripts/``` folder
- Sources for the database upgrade process are in ```/database/upgrade``` folder
- Upgrade script is started from the reposcan container and is placed in root folder of the container (```dbupgrade.sh```)
- Also I wrote some tutorial in ```README.md``` inside database folder

feat(database): add database upgrade scripts and tutorial

---

database/Dockerfile.centos
docker-compose-dbdocs.yml
docker-compose.yml
run_tests.sh

re-introduce 2 dockerfiles because registry.redhat.io doesn't allow unauthenticated download

feat(database): upgrade to PostgreSQL 12

---

webapp/app.py
webapp/cache.py

- healthchecks won't fail because webapp stays responsive
- other apps can detect refreshing state by 503 code and retry instead of time out

don't block APIs when doing refresh and return 503 instead

---

docker-compose.devel-podman.yml
docker-compose.devel.yml

With podman-compose from Fedora 31 the command attribute from files docker-compose-devel* is not replaced by command from another file. The commands are joined. This fixes the commands to be replaced by command from another docker-compose file.

Fix command in devel docker composes for podman-compose

---

webapp/rpm_pkg_names.py
webapp/srpm_pkg_names.py
webapp/test/test_rpm_pkg_names.py
webapp/test/test_srpm_pkg_names.py

- Now the package will be displayed as empty ("package_name" {}) only when it exists in the database.

Fix rpms and srpms responses

---

Dockerfile.test
Pipfile.lock
reposcan/Pipfile.lock
webapp/Pipfile.lock
webapp/test/test_run_app.py
websocket/Pipfile.lock

Pylint 2.5.0 no longer allows python -m pylint ... to import user code. Previously, it added the current working directory as the first element of sys.path. This opened up a potential security hole where pylint would import user level code as long as that code resided in modules having the same name as stdlib or pylint's own modules.

chore: re-lock dependencies to update pylint

---

Dockerfile.test
reposcan/Dockerfile
webapp/Dockerfile
webapp/Dockerfile-qe
webapp_utils/Dockerfile
websocket/Dockerfile

https://github.com/pypa/pipenv/issues/4188
PIPENV_PYUP_API_KEY= can be removed when pipenv-2020.X.X is released

chore: pipenv check workaround

---

webapp/srpm_pkg_names.py

This fixes the timeout in /names/srpms/<name> and optimizes response time. On my local setup I got response time for kernel package name from 102 sec to 8 sec.

Fix srpm API performance that resulted in timeouts

---

webapp/test/data/cache.yml
webapp/test/test_app.py
webapp/test/test_cache.py
webapp/test/test_modularity.py
webapp/test/test_pkgtree.py
webapp/updates.py

- Updated not to return **modules related** updates, cves and erratas by default but only when modules_list is explicitly included into the request.
- Updated testing cache.yml to contain also non-module updates for better testing.
- Updated tests according to previous changes.

Removed updates when modules_list is not provided

---

common/slack_notifications.py
reposcan/repodata/repository_controller.py

reposcan: [ERROR] Internal server error <-9223363273888645507>'Traceback (most recent call last):\n  File "/vmaas/reposcan/repodata/repository_controller.py", line 81, in _check_cert_expiration_date\n    loaded_cert = crypto.load_certificate(crypto.FILETYPE_PEM, cert)\n  File "/usr/local/lib/python3.6/site-packages/OpenSSL/crypto.py", line 1794, in load_certificate\n    _raise_current_error()\n  File "/usr/local/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue\n    raise exception_type(errors)\nOpenSSL.crypto.Error: [(\'PEM routines\', \'get_name\', \'no start line\')]\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/vmaas/reposcan/reposcan.py", line 518, in run_task\n …

fix(reposcan): fixing ISE in prepare msg function

---

.github/workflows/ci.yml

fixes 
```
Error: Unable to process command '::add-path::/home/runner/work/vmaas/vmaas/oc' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

chore: use redhat-actions/oc-installer

---

common/config.py
docker-compose.devel.yml
docker-compose.yml
entrypoint.sh
wait_for_services.py

- fix waiting for DB when POSTGRESQL_DATABASE is not set
- fix rsync port when it is not deployed by Clowder
- add `hostname` to docker-compose, it is referenced in wait_for_services.py

fix: waiting for DB and rsync port in e2e-deploy and docker-compose

---

deploy/clowdapp.yaml
reposcan/main.py
reposcan/reposcan.healthz.spec.yaml
reposcan/reposcan.py
reposcan/reposcan.spec.yaml
reposcan/test/test_case.py
reposcan/test/test_run_reposcan.py
webapp/app.py
webapp/main.py
webapp/test/test_app.py
webapp/test/test_run_app.py
webapp/webapp.v1.spec.yaml
webapp/webapp.v2.spec.yaml
webapp/webapp.v3.spec.yaml
webapp_utils/app.py
webapp_utils/webapp-utils-healthz.yml
webapp_utils/webapp-utils.yml
websocket/websocket.py

Healthz endpoint in webapp is added through aiohttp instance, because the connexion API does not allow having empty basepath for aiohttp.

chore: refactor and mirror health endpoint for clowder

---

reposcan/reposcan.py
reposcan/reposcan.spec.yaml

Current approach results in issues when using multiple baseurls. This change adds multiple entries per one content set, and later pull request will remove support for multiple baseurls. (Result will be the same, but we will be able to choose what baseurl template should be applied to what releasevers within one content set).

feat(reposcan): accept lists for content set data

---

reposcan/reposcan.py
reposcan/reposcan.spec.yaml

In current state we don't allow repolists without any cert. Either one is provided, or default is used. This allows opting out of the default cert.

feat(reposcan): allow repolists to opt_out of default certificates

---

pr_check.sh

`vmaas` and `vulnerability-engine` are defined as components of `vulnerability` app in `app-interface` repo. We need to deploy only `vmaas` to ephemeral env. 
https://github.com/RedHatInsights/bonfire/pull/58 allows to deploy selected components

chore: deploy vmaas component of vulnerability app

---

vmaas/reposcan/reposcan.py

Added a code to split the `REPOLIST_PATH` on commas, and use individual elements as separate repolists.
We might want to rename this variable to `REPOLIST_PATHS`.

Accept multiple repolists for git sync

---

vmaas/reposcan/database/product_store.py

Syncing a repolist with multiple items per single content_set resulted in an error. Fixing this.

Fix multiple content-set syncing process

---

deploy/clowdapp.yaml

VULN-1909
for smoother transition, especially for Patch team if we deploy clowderized vmaas to prod sooner than Patch
and add an external route for vmaas like we used to have with old deployment

chore(clowder): smooth transition with legacy ports

---

wait_for_services.py

Traceback (most recent call last):
File "../../wait_for_services.py", line 72, in <module>
main()
File "../../wait_for_services.py", line 61, in main
service="Reposcan API"
File "../../wait_for_services.py", line 35, in wait
time.sleep(delay)
TypeError: bye() takes 0 positional arguments but 2 were given

chore: signal handler takes 2 argmuents

---

wait_for_services.py

requests will hang if no timeout is set which causes unnecessary pod restarts just after deploy

fix: set timeout for requests while waiting for services

---

vmaas/webapp/pkgtree.py
vmaas/webapp/test/test_pkgtree.py

- Exclude packages without time info (without errata) when "modified_since" used in request
VMAAS-1346

fix(webapp): Fix /pkgtree endpoint when "modified_since" used

---

vmaas/webapp/errata.py

fixing
"RHSA-2018:0512": { ...
"release_versions": [ "6.10", "6.9", "6ComputeNode", "6Server", "6Client", "6Workstation", null ]
}

VMAAS-1392: remove empty release versions from list

---

vmaas/websocket/websocket.py

VULN-2022
This causes issues in ephemeral, webapp is advertised as ready when the latest dump is None, which causes webapp to have empty data.

fix(websocket): do not advertise None vmaas cache version

---

deploy/clowdapp.yaml

This resolves issues when deployed with Istio.
Do not merge yet until Clowder changes are pushed to Prod.

Set private port protocol to tcp for rsync

---

vmaas-go/go.mod
vmaas-go/go.sum

Updates were incorrect for repos with empty releasever, fixed by https://github.com/RedHatInsights/vmaas-lib/commit/3ec8712cdaa5638902ee1d2b6aecf31b3c3de0a8

fix(vmaas-go): updates when releasever in repo is empty

---

Dockerfile
deploy/clowdapp.yaml
vmaas-go/go.mod
vmaas-go/go.sum

- fix issue with cache reload - fixed by https://github.com/RedHatInsights/vmaas-lib/pull/14/files
- lower GOGC to 25% since GC is still not run soon enough

fix(vmaas-go): cache reload, adjust GOGC

---

vmaas/common/webapp_utils.py

update for single invalid package (erp-handler-0:-.i386) returns:
"update_list": {
"erp-handler-0:-.i386": {}
}
but when there are 2 invalid packages in the request, ("package_list": ["cel-handler-0:-.i386, erp-handler-0:-.i386"]) then it returns 400. the expected response is:
"update_list": {
"cel-handler-0:-.i386": {},
"erp-handler-0:-.i386": {}
}

fix: inconsistent response for invalid packages

---

deploy/clowdapp.yaml

- add ability to set CPU/Memory requests/limits only for webapp-go
- set CPU limit = 2 to use parallelization at least for cache load
- GOMAXPROCS has to be set the same as the CPU limit (but it needs to be integer), higher gomaxprocs than cpu limit affects app performance, e.g. see benchmark in https://github.com/uber-go/automaxprocs#performance

chore(vmaas-go) adjust cpu limit and gomaxprocs

---

database/upgrade_scripts/016-repo_last_change.sql
database/vmaas_db_postgresql.sql
vmaas/reposcan/exporter.py
vmaas/webapp/cache.py

Lets store the last change of every repository done by vmaas. So that in vmaas-sync for Patch/Vulnerability, we can use this timestamp instead of "revision" timestamp for `modified_since` parameter. Since the revision timestamp is not in "our hands" to modify and by this new timestamp we can detect timestamp when repo changed in vmaas (and not in RedHat CDN).

feat: store timestamp of last change of given repository

---

database/upgrade_scripts/017-csaf_file_table.sql
database/vmaas_db_postgresql.sql
deploy/clowdapp.yaml
poetry.lock
pyproject.toml
vmaas/common/batch_list.py
vmaas/reposcan/database/csaf_store.py
vmaas/reposcan/mnm.py
vmaas/reposcan/redhatcsaf/csaf_controller.py
vmaas/reposcan/redhatcsaf/modeling.py

feat(csaf): initial implementation to download csaf files

---

vmaas/common/config.py
vmaas/common/logging_utils.py
vmaas/common/strtobool.py
vmaas/reposcan/redhatcsaf/csaf_controller.py
vmaas/reposcan/redhatoval/oval_controller.py
vmaas/reposcan/repodata/updateinfo.py
vmaas/reposcan/reposcan.py
vmaas/webapp/app.py

use same strtobool implementation as we are using in vulnerability-engine
- distutils is deprecated since python3.10
- distutils.util.strtobool returns int instead of bool

chore: replace strtobool by custom impl

---

deploy/clowdapp.yaml
vmaas/common/config.py
vmaas/reposcan/database/csaf_store.py
vmaas/reposcan/redhatcsaf/csaf_controller.py
vmaas/reposcan/redhatcsaf/modeling.py
vmaas/reposcan/redhatcsaf/test/cve-2023-0030.json
vmaas/reposcan/redhatcsaf/test/cve-2023-0049.json
vmaas/reposcan/redhatcsaf/test/cve-2023-1017.json
vmaas/reposcan/redhatcsaf/test/test_controller.py
vmaas/reposcan/redhatcsaf/test/test_modeling.py

feat(csaf): vulnerabilities parsing

---

.github/workflows/tests.yml
poetry.lock
pyproject.toml
vmaas/reposcan/redhatoval/definitions_file.py
vmaas/reposcan/reposcan.py

- run mypy in github actions
- errors in csaf types are resolved in https://github.com/RedHatInsights/vmaas/pull/1067
- remove unnecessary steps from `tests` and run flake8 in poetry venv

chore: run mypy

---

build_deploy.sh

The build is often using cached resources when building which means we don't always get the most up to date packages. Adding no-cache to build_deploy so we can ensure we always build fresh

build: Add --no-cache option to build deploy

---

.github/workflows/tests.yml
database/upgrade_scripts/020-csaf_tables2.sql
database/vmaas_db_postgresql.sql
pyproject.toml
run_tests.sh
vmaas/common/batch_list.py
vmaas/common/config.py
vmaas/common/date_utils.py
vmaas/common/logging_utils.py
vmaas/common/rpm_utils.py
vmaas/reposcan/conftest.py
vmaas/reposcan/database/cpe_store.py
vmaas/reposcan/database/csaf_store.py
vmaas/reposcan/database/object_store.py
vmaas/reposcan/database/test/test_csaf.py
vmaas/reposcan/download/downloader.py
vmaas/reposcan/redhatcsaf/csaf_controller.py
vmaas/reposcan/redhatcsaf/modeling.py
vmaas/reposcan/redhatcsaf/test/test_controller.py
vmaas/reposcan/redhatcsaf/test/test_modeling.py

RHINENG-7862
further changes will be added once #1073 is completed
(it's not `cve_detail` table but `cve`, I'll fix the diagram later, code should be correct)

fix(csaf): finalize db schema

---

vmaas/reposcan/redhatcsaf/csaf_controller.py

`files_to_sync` can be generator if we are syncing only out_of_date files, `len(list(files_to_sync))=0` because the `files_to_sync` generator was already iterated when items were added to batches
```
2024-03-26 13:08:54,226:INFO:vmaas.reposcan.redhatcsaf.csaf_controller:0 CSAF files need to be synced.
2024-03-26 13:08:54,226:INFO:vmaas.reposcan.redhatcsaf.csaf_controller:Syncing a batch of 500 CSAF files [1/2]
```

chore(csaf): fix count of files in log

---

vmaas/webapp/repos.py
vmaas/webapp/webapp.v3.spec.yaml

RHINENG-9690
endpoint response time with stage data:
- page_size=500 (value used by Patch in vmaas sync), modified_since=2024-01-01T00:00:00Z, 947 repos returned on first page
- before: 0.059s
- with show_packages: 0.114s
- page_size=500, modified_since=2000-01-01T00:00:00Z, 1167 repos returned on first page
- before: 0.056s
- with show_packages: 1.106s
it is significantly slower, especially if someone wants to use very old date for modified_since but I don't think it is worth optimizing it at the moment, let's see how it performs in openshift and if we see some latency or memory issues

feat: list modified packages in modified repos

---

vmaas/reposcan/database/csaf_store.py
vmaas/reposcan/database/test/test_csaf.py
vmaas/reposcan/redhatcsaf/modeling.py

vmaas-reposcan          | vmaas-reposcan 2024-06-03 17:50:17,781:ERROR:vmaas.reposcan.database.object_store:Failed to import csaf file to DB: 'Traceback (most recent call last):\n  File "/vmaas/vmaas/reposcan/database/csaf_store.py", line 75, in _save_csaf_files\n    cur.execute("select id, name from csaf_file where name in %s", (tuple(files),))\npsycopg2.errors.SyntaxError: syntax error at or near ")"\nLINE 1: select id, name from csaf_file where name in ()\n                                                      ^\n'|
RHINENG-10604

fix(csaf): syntax error with IN query

---

.github/workflows/tests.yml
run_tests.sh
vmaas-go/base/core/config.go
vmaas-go/base/utils/config.go
vmaas-go/webapp/controllers/updates.go
vmaas-go/webapp/controllers/utils.go
vmaas-go/webapp/controllers/utils_test.go
vmaas-go/webapp/controllers/vulnerabilities.go

feat(csaf): use csaf evaluation by default 

---

pr_check.sh

chore(ephemeral): remove --no-remove-resources

---

vmaas/webapp/repos.py
vmaas/webapp/webapp.v3.spec.yaml

repository may be re-generated but no RPM erratum added (push of container images triggers RPM repodata re-generation)

fix(webapp): don't show repositories without changed packages

---

vmaas/reposcan/database/csaf_store.py
vmaas/reposcan/database/test/test_csaf.py
vmaas/reposcan/redhatcsaf/modeling.py
vmaas/reposcan/redhatcsaf/test/test_modeling.py

fix: remove removed csaf files from db

---

vmaas-go/go.mod
vmaas-go/go.sum

fix: skip cves missing in mapping

---

.github/workflows/safety.yml
.github/workflows/tests.yml
Dockerfile
deploy/clowdapp.yaml
docker-compose.test.yml
docker-compose.yml
entrypoint.sh
poetry.lock
pyproject.toml
scripts/poetry-lock.sh

RHINENG-14727
RHINENG-14647
RHINENG-14648

chore: upgrade python version

---

deploy/clowdapp.yaml
vmaas-go/base/utils/config.go
vmaas-go/webapp/controllers/cves.go
vmaas-go/webapp/controllers/utils.go
vmaas-go/webapp/routes/routes.go

feat(webapp): add go controller for cves endpoint

---

deploy/clowdapp.yaml
vmaas-go/base/utils/config.go
vmaas-go/go.mod
vmaas-go/go.sum
vmaas-go/webapp/controllers/errata.go
vmaas-go/webapp/routes/routes.go

feat(webapp): add go controller for errata endpoint

---

vmaas/reposcan/database/test/test_repository_store.py

chore: fix theoretical sql injection

---

vmaas-go/go.mod
vmaas-go/go.sum
vmaas/reposcan/exporter.py

feat(reposcan): export OS release system profiles to dump

---

deploy/clowdapp.yaml
vmaas-go/base/utils/config.go
vmaas-go/go.mod
vmaas-go/go.sum
vmaas-go/webapp/controllers/repos.go
vmaas-go/webapp/routes/routes.go

feat(webapp): add go controller for repos endpoint

---

deploy/clowdapp.yaml
vmaas-go/.golangci.yml
vmaas-go/base/utils/config.go
vmaas-go/go.mod
vmaas-go/go.sum
vmaas-go/webapp/controllers/packages.go
vmaas-go/webapp/routes/routes.go

feat(webapp): add go controller for packages endpoint
